apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snaplink-sso

resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml

configMapGenerator:
  - name: snaplink-stripe-adapter-settings
    envs:
      - settings.env
  - name: snaplink-stripe-adapter-bindings
    files:
      - bindings.json

labels:
  - pairs:
      app.kubernetes.io/part-of: snaplink-sso
    includeSelectors: false
