apiVersion: v1
kind: Service
metadata:
  name: snaplink-audit-provisioner
spec:
  selector:
    app.kubernetes.io/name: snaplink-audit-provisioner
  ports:
    - name: status
      port: 8092
      targetPort: status
