package generate

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"testing"
)

// repoRoot returns the absolute path to the module root: three directories
// up from this test file (cmd/sso-ctl/generate -> cmd/sso-ctl -> cmd ->
// root). Derived from runtime.Caller rather than os.Getwd so it's correct
// regardless of where `go test` is invoked from.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed to resolve this test file's path")
	}
	return filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(thisFile))))
}

var goDirectiveRE = regexp.MustCompile(`(?m)^go (\S+)`)

// goDirective extracts the "go X.Y.Z" line from the real repo's go.mod so
// the synthetic build module below declares a compatible language version
// instead of a hardcoded one that could drift out of sync.
func goDirective(t *testing.T, root string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		t.Fatalf("read %s/go.mod: %v", root, err)
	}
	m := goDirectiveRE.FindSubmatch(data)
	if m == nil {
		t.Fatalf("no 'go X.Y.Z' directive found in %s/go.mod", root)
	}
	return string(m[1])
}

// newBuildableModule turns dir into a standalone Go module that requires
// (and locally replaces) the real github.com/yangwb1123/snaplink module. This is
// how a scaffolded file gets compiled in COMPLETE isolation from the real
// repo tree: nothing generated by this test ever lands inside the real
// module's own directories, so it can never trip the real repo's own
// maintainability/architecture gates (directory_fanout_test.go,
// architecture_layer_test.go) even transiently. go.sum is copied verbatim
// from the real repo so every transitive dependency resolves from the
// already-populated local module cache with no network access.
func newBuildableModule(t *testing.T, dir, root string) {
	t.Helper()
	goVer := goDirective(t, root)
	modContent := "module scaffoldbuildtest\n\ngo " + goVer + "\n\n" +
		"require github.com/yangwb1123/snaplink v0.0.0-00010101000000-000000000000\n\n" +
		"replace github.com/yangwb1123/snaplink => " + root + "\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(modContent), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	sum, err := os.ReadFile(filepath.Join(root, "go.sum"))
	if err != nil {
		t.Fatalf("read %s/go.sum: %v", root, err)
	}
	if err := os.WriteFile(filepath.Join(dir, "go.sum"), sum, 0o644); err != nil {
		t.Fatalf("write go.sum: %v", err)
	}
}

// TestGeneratedScaffoldsCompile is the regression test guaranteeing every
// component kind sso-ctl generate can produce actually BUILDS — not just
// "looks plausible" or "parses as a valid template". It generates each kind
// into its own isolated temporary module (via t.TempDir() + newBuildableModule
// above) and shells out to a real `go build ./...` (os/exec, not a mock or a
// text/template dry-run), asserting success.
//
// The gate has three layers, in order:
//  1. contract assertions on the generated artifact (scaffold_contract_test.go):
//     every ErrorBody code must be registered in docs/error-codes.md, no legacy
//     path/port patterns or inline path literals may appear, every core.Path*
//     reference must exist in shared/core/consts.go, and the handler kind must
//     teach the form-urlencoded Content-Type guard before any ctx.Bind.
//  2. `go build ./...` — compiles in COMPLETE isolation from the real repo
//     tree.
//  3. `go vet ./...` — static analysis on the same isolated module (a
//     template can regress into output that compiles but still fails vet).
//
// This is the regression the prior templates would have failed: they parsed
// and executed fine while producing output with unused imports, a return
// value of the wrong type (a string error-code constant where an `error` was
// required), and — for the grant template — a completely fabricated
// interface shape (core.TokenRequest/TokenResponse/OAuthError) that doesn't
// exist anywhere in this module. None of that is visible to template
// execution; only a real compiler catches it, which is why this test invokes
// one.
func TestGeneratedScaffoldsCompile(t *testing.T) {
	root := repoRoot(t)

	cases := []struct {
		kind string
		pkg  string
		name string
	}{
		{"authenticator", "authenticators", "totp"},
		{"store", "infrastructure/redis", "redis"},
		{"handler", "internal/handler", "webhook"},
		{"grant", "protocols/grants", "device-code"},
	}

	for _, tc := range cases {
		t.Run(tc.kind, func(t *testing.T) {
			t.Parallel()

			dir := t.TempDir()
			newBuildableModule(t, dir, root)

			outputDir := filepath.Join(dir, "gen", filepath.FromSlash(tc.pkg))
			scaffold := NewScaffold(tc.kind, tc.name, tc.pkg, "integration-test "+tc.kind)
			if err := scaffold.Generate(outputDir); err != nil {
				t.Fatalf("Generate(%s): %v", tc.kind, err)
			}

			generated, err := os.ReadFile(generatedFile(tc.kind, tc.name, outputDir))
			if err != nil {
				t.Fatalf("read generated %s scaffold: %v", tc.kind, err)
			}
			assertRegisteredErrorCodes(t, tc.kind, generated, root)
			assertNoLegacyPathPort(t, tc.kind, generated)
			assertNoPathLiterals(t, tc.kind, generated, root)
			assertKindInvariants(t, tc.kind, generated, root)

			for _, tool := range []string{"build", "vet"} {
				cmd := exec.Command("go", tool, "./...")
				cmd.Dir = dir
				cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod", "GOPROXY=off")
				out, err := cmd.CombinedOutput()
				if err != nil {
					t.Fatalf("generated %s scaffold does not pass go %s:\n%s", tc.kind, tool, out)
				}
			}
		})
	}
}
