version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - gomod
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope

  - package-ecosystem: gomod
    directory: "/kms/awskms"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - awskms

  - package-ecosystem: gomod
    directory: "/kms/gcpkms"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - gcpkms

  - package-ecosystem: docker
    directory: "/deploy/compose"
    schedule:
      interval: monthly
    labels:
      - docker
