#!/usr/bin/env bash
# GATE: 检查 .go 文件是否超过 500 行
set -euo pipefail
MAX_LINES=500; EXIT_CODE=0
EXEMPTIONS=("handlers.go" "server_extensions.go" "sso.go" "handler.go" "config/config.go" "cmd/sso-server/main.go" "core/types.go" "core/consts.go" "signing_key_aggregation.go" "defaultimpl/ed25519_jwt_issuer.go" "defaultimpl/ecdsa_jwt_issuer.go" "defaultimpl/rsa_jwt_issuer.go" "defaultimpl/vaulttransit/signer.go" "defaultimpl/vaulttransit/signer_test.go" "defaultimpl/push_mfa_provider.go" "defaultimpl/push_mfa_provider_test.go" "defaultimpl/sqlite/clients.go" "defaultimpl/sqlite/clients_test.go" "defaultimpl/sqlite/refresh_tokens.go" "accessors.go" "client_store_cache_test.go" "signing_key_aggregation_test.go" "audit/recorder_events.go" "audit/sqlite/sink.go" "metrics/metrics.go" "anomaly/runner.go" "snapshot/restorer.go" "authenticators/webauthn/webauthn.go" "authenticators/authenticators_test.go" "cmd/sso-import/main.go" "cmd/sso-server/webauthn.go" "cmd/sso-server/webauthn_test.go" "cmd/sso-server/mfa_test.go" "permissions/sqlite/sqlite.go" "signingkeys/etcd/etcd.go" "tenant/sqlite/sqlite.go" "federation/entity_statement.go" "federation/trust_chain.go" "federation/trust_chain_test.go" "federation/trust_marks.go" "federation/trust_marks_test.go" "federation/trust_marks_resolved_test.go" "federation/trust_marks_resolved_dos_test.go" "federation/registration.go" "federation/registration_test.go" "federation/constraints.go" "federation/constraints_test.go" "federation/metadata_policy.go" "caep/receiver.go" "caep/receiver_test.go" "saml/saml.go" "saml/saml_slo_test.go" "saml/idp/fanout.go" "saml/idp/fanout_test.go" "saml/idp/frontchannel_slo.go" "saml/idp/frontchannel_slo_test.go" "saml/idp/slo_test.go" "saml/sp/slo.go" "saml/sp/slo_test.go" "ldap/authenticator_test.go" "kerberos/kerberos_test.go" "radius/exchange_roundtrip_test.go" "extauthz/authz_test.go" "scim/handler.go" "scim/handler_test.go" "kms/azurekeyvault/signer.go" "kms/azurekeyvault/signer_test.go" "kms/pkcs11/signer_test.go" "kms/gcpkms/signer_test.go" "test/tenant_middleware_test.go" "test/refresh_token_test.go" "test/mfa_test.go" "test/scope_authorization_test.go" "test/mesh_authorize_test.go" "test/auth_code_test.go" "test/me_sessions_test.go" "test/handle_token_exchange_test.go" "test/consent_test.go" "test/multialg_auth_test.go" "test/rar_test.go" "grpcserver/admin_tenants_test.go")
is_exempt() { local f="$1"; for e in "${EXEMPTIONS[@]}"; do [[ "$f" == *"$e" ]] && return 0; done; return 1; }
check_file() { local f="$1"; [[ "$f" == *.go ]] || return 0; [[ "$f" != gen/proto/* ]] || return 0; is_exempt "$f" && return 0; local l=$(wc -l < "$f"); if (( l > MAX_LINES )); then echo "  FAIL: $f ($l lines, max $MAX_LINES)"; EXIT_CODE=1; fi; }
if [[ $# -gt 0 ]]; then for f in "$@"; do check_file "$f"; done; else while IFS= read -r -d '' f; do check_file "$f"; done < <(find . -name '*.go' -not -path './.git/*' -not -path './.claude/*' -not -path './gen/proto/*' -not -path './vendor/*' -print0); fi
[[ $EXIT_CODE -eq 0 ]] && echo "PASS: filesize" || { echo "FAIL: split before continuing"; exit 1; }
