{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snaplink-audit-provisioner.serviceAccountName" . }}
automountServiceAccountToken: false
{{- end }}
