// Code generated by cmd/gensdk (--lang=ts). DO NOT EDIT.
// Source: docs/openapi.yaml (snaplink/sso HTTP API 0.1.0). Regenerate: go run ./cmd/gensdk --lang=ts
//
// Minimal, hand-scoped TypeScript client — see docs/sdks/typescript/README.md
// for exactly what operationId set this covers (core OAuth2/OIDC + token
// lifecycle + self-service + a small representative admin sample) and what
// is deliberately deferred (the full ~150-route admin/SCIM/CAEP/federation
// surface). Every method name is the spec's operationId verbatim — no
// derived/shortened aliasing — so a call site is grep-able straight back to
// its docs/openapi.yaml operation.

export type FetchLike = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;

export interface SSOClientOptions {
  /** Base URL of the snaplink/sso deployment, e.g. "https://sso.example.com". */
  baseUrl: string;
  /** This application's registered client_id. */
  clientId?: string;
  /** Confidential client secret. Server-side use only; sent with HTTP Basic. */
  clientSecret?: string;
  /** Per-request timeout in milliseconds. Omit to use the runtime fetch default. */
  requestTimeoutMs?: number;
  /** Injectable fetch (tests, non-global runtimes). Defaults to globalThis.fetch. */
  fetch?: FetchLike;
  /** Returns the bearer token for auth-required calls (getMe, revokeMySessions, ...).
   *  Omit it: after login() the SDK holds the access token and auto-attaches it. */
  getAccessToken?: () => string | undefined | Promise<string | undefined>;
}

/** Thrown on any non-2xx response; carries the parsed ErrorResponse when the body was JSON. */
export class SSOError extends Error {
  constructor(
    public status: number,
    public error?: string,
    public errorDescription?: string,
  ) {
    super(errorDescription || error || `sso request failed with status ${status}`);
    this.name = "SSOError";
  }
}

interface requestOptions {
  query?: Record<string, string | number | boolean | undefined>;
  body?: unknown;
  auth?: boolean;
  clientAuth?: boolean;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringValue(value: unknown): string | undefined {
  return typeof value === "string" && value !== "" ? value : undefined;
}

function encodeBasicCredentials(clientId: string, clientSecret: string): string {
  const bytes = new TextEncoder().encode(clientId + ":" + clientSecret);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

// ---- Types (generated from components.schemas) ----

export interface AuditEvent {
  actor_id?: string;
  actor_ip?: string;
  client_id?: string;
  hash?: string;
  id: string;
  /** Free-form key/value pairs (tenant.*, geo.*, plus */
  metadata?: Record<string, string>;
  outcome: "success" | "failure";
  parent_span_id?: string;
  /** Present when WithHashChain is enabled. */
  prev_hash?: string;
  provider?: string;
  reason?: string;
  request_id?: string;
  session_id?: string;
  span_id?: string;
  timestamp: string;
  token_id?: string;
  token_strategy?: string;
  trace_id?: string;
  /** Canonical event type (login, logout, refresh_token_issued, ...). */
  type: string;
  user_agent?: string;
}

export interface AuditEventList {
  count: number;
  events: AuditEvent[];
}

export interface AuthorizationCodeResponse {
  /** Short-lived, single-use authorization code to exchange at /token. */
  code: string;
  /** RFC 9207 authorization-server issuer identifier. */
  iss: string;
  /** Opaque state echoed when it was supplied in LoginRequest. */
  state?: string;
}

/** One element of RFC 9396 Rich Authorization Requests */
export interface AuthorizationDetail {
  /** RFC 9396 §3.3 — action verbs (read, write, transfer). */
  actions?: string[];
  /** RFC 9396 §3.4 — data categories. Type-specific. */
  datatypes?: string[];
  /** RFC 9396 §3.5 — opaque identifier scoping the grant. */
  identifier?: string;
  /** RFC 9396 §3.2 — URIs identifying resource servers the */
  locations?: string[];
  /** RFC 9396 §3.6 — privilege strings within the resource. */
  privileges?: string[];
  /** URI or string identifying the action class. Allowlisted */
  type: string;
}

export interface Button {
  code: string;
  name?: string;
  permission?: string;
}

export interface ClientMetadata {
  /** Nanoseconds. */
  access_token_ttl?: number;
  active?: boolean;
  /** When true, refuses provider=password at /auth/login for this */
  allow_passwordless_only?: boolean;
  allowed_authenticators?: string[];
  allowed_authorization_details_types?: string[];
  allowed_pkce_methods?: string[];
  allowed_request_uris?: string[];
  allowed_resources?: string[];
  allowed_scopes?: string[];
  backchannel_logout_uri?: string;
  device_code_poll_interval?: number;
  device_code_ttl?: number;
  frontchannel_logout_uri?: string;
  id: string;
  jwks?: Record<string, unknown>[];
  name?: string;
  post_logout_redirect_uris?: string[];
  redirect_uris?: string[];
  /** Nanoseconds. */
  refresh_token_ttl?: number;
  require_par?: boolean;
  require_pkce?: boolean;
  require_signed_request_object?: boolean;
  sector_identifier_uri?: string;
  subject_type?: "public" | "pairwise";
  tenant_id?: string;
  token_strategy?: "jwt" | "session";
  userinfo_signed_response_alg?: string;
}

export interface DCRRequest {
  allowed_authenticators?: string[];
  allowed_resources?: string[];
  client_name?: string;
  contacts?: string[];
  grant_types?: string[];
  post_logout_redirect_uris?: string[];
  redirect_uris?: string[];
  require_pkce?: boolean;
  response_types?: string[];
  /** Space-delimited scope list. */
  scope?: string;
  tenant_id?: string;
  /** `none` opts out of secret issuance (public client / PKCE */
  token_endpoint_auth_method?: "client_secret_basic" | "client_secret_post" | "private_key_jwt" | "none";
  /** Names the registered TokenIssuer this client uses; */
  token_strategy?: "jwt" | "session";
}

export interface DCRResponse {
  allowed_authenticators?: string[];
  allowed_resources?: string[];
  client_id: string;
  /** Unix seconds. */
  client_id_issued_at: number;
  client_name?: string;
  /** Omitted when token_endpoint_auth_method=none. */
  client_secret?: string;
  /** Unix seconds; `0` means "never expires" per RFC 7591 */
  client_secret_expires_at: number;
  contacts?: string[];
  grant_types?: string[];
  post_logout_redirect_uris?: string[];
  redirect_uris?: string[];
  /** RFC 7592 management bearer — authenticates subsequent */
  registration_access_token?: string;
  registration_client_uri?: string;
  require_pkce?: boolean;
  response_types?: string[];
  scope?: string;
  token_endpoint_auth_method?: string;
  token_strategy?: string;
}

export interface DeviceCodeRequest {
  client_id: string;
  nonce?: string;
  resource?: string[];
  scope?: string;
}

export interface DeviceCodeResponse {
  /** The device polls /token with this. */
  device_code: string;
  expires_in: number;
  /** Minimum seconds between /token polls. */
  interval: number;
  user_code: string;
  verification_uri: string;
  /** Same URI with `?user_code=` pre-filled — QR-friendly. */
  verification_uri_complete?: string;
}

export interface DeviceVerifyRequest {
  /** `true` to authorize; `false` to deny (device's next */
  approve: boolean;
  /** Case-insensitive and dash-insensitive. `WXYZ-1234`, */
  user_code: string;
}

/** Returned instead of `IntrospectResponse` when the request used */
export interface IntrospectBatchResponse {
  /** One `IntrospectResponse` per requested token, in the SAME order as the request's `tokens` array. */
  results: IntrospectResponse[];
}

export interface IntrospectRequest {
  client_id?: string;
  client_secret?: string;
  /** The token to introspect. */
  token: string;
  /** Lookup shortcut. Server falls back to the other store */
  token_type_hint?: "access_token" | "refresh_token";
  /** Opt-in batch mode (`oauth.introspection.batch_enabled` / */
  tokens?: string[];
}

export interface IntrospectResponse {
  /** `false` covers expired / revoked / never-issued */
  active: boolean;
  aud?: string | string[];
  client_id?: string;
  /** RFC 7800 confirmation method. Present when the token was */
  cnf?: Record<string, unknown>;
  /** Unix expiry seconds. */
  exp?: number;
  /** Unix issued-at seconds. */
  iat?: number;
  iss?: string;
  jti?: string;
  /** Unix time this still-active token needs renewal, an early */
  renew_after?: number;
  scope?: string;
  sub?: string;
  token_type?: string;
  username?: string;
}

export interface JWK {
  alg?: string;
  crv?: string;
  /** First 8 bytes of sha256(pubkey), base64url-encoded. */
  kid: string;
  kty: string;
  use: string;
  /** Base64url-encoded public key bytes. */
  x?: string;
}

export interface JWKS {
  keys: JWK[];
}

export interface ListRolesResponse {
  /** Opaque cursor for the next page; empty on the last page. */
  nextPageToken: string;
  roles: Role[];
  /** Total roles in the client registry. */
  totalSize: number;
}

/** A LOCAL (password-authenticated) user — distinct from AdminUser */
export interface LocalUserResponse {
  attributes?: Record<string, string>;
  created_at: string;
  display_name?: string;
  email?: string;
  external_id?: string;
  id: string;
  name?: string;
  provider?: string;
  updated_at: string;
  username?: string;
}

export interface LoginDiscoveryResponse {
  /** Authenticator names this client may use. */
  providers: string[];
}

export interface LoginRequest {
  /** RFC 9396 Rich Authorization Requests. Each element MUST */
  authorization_details?: AuthorizationDetail[];
  /** Registered Client.ID (per cmd/sso-server/config.yaml `clients[]`). */
  client_id: string;
  /** RFC 7636 PKCE code challenge for authorization-code login. */
  code_challenge?: string;
  /** RFC 7636 PKCE transformation; S256 is recommended and may be required. */
  code_challenge_method?: "plain" | "S256";
  /** Provider-specific credential map. Standard keys: */
  credential?: Record<string, string>;
  /** Opaque "remember this device" grant minted by a prior */
  device_token?: string;
  /** OIDC nonce bound to a subsequently issued ID token. */
  nonce?: string;
  /** Authenticator name; omit for discovery. */
  provider?: string;
  /** Registered redirect URI bound to the authorization code. */
  redirect_uri?: string;
  /** RFC 8707 resource indicators. Each value MUST be in the */
  resource?: string[];
  /** Request an OAuth 2.0 authorization code instead of direct token minting. */
  response_type?: "code";
  scope?: string[];
  /** Opaque value echoed back to redirect-based flows. */
  state?: string;
}

export interface LoginResponse {
  /** Ed25519 JWT (when client uses `token_strategy: jwt`) or opaque session token (when `session`). */
  access_token: string;
  /** ISO 3166-1 alpha-2; populated when geo middleware is wired. */
  country_code?: string;
  /** Present only on a `POST /auth/mfa` completion where the */
  device_token?: string;
  /** Token lifetime in seconds. */
  expires_in: number;
  /** OIDC ID token, present when the granted scope includes openid. */
  id_token?: string;
  /** RFC 9207 authorization-server issuer identifier. */
  iss: string;
  /** Present when `permissions.embed_in_login: true`. */
  menus?: MenuTree;
  /** Advisory UX nudge — present (`true`) only when */
  passkey_enrollment_recommended?: boolean;
  /** Advisory metadata accompanying `passkey_enrollment_recommended` */
  passkey_recovery_allowed?: boolean;
  /** Present when `permissions.embed_in_login: true`. */
  permissions?: Permission[];
  /** BCP-47 tag; populated when geo middleware is wired. */
  recommended_language?: string;
  refresh_token?: string;
  /** Present when `permissions.embed_in_login: true`. */
  roles?: Role[];
  /** Space-delimited scope list. */
  scope?: string;
  /** Which regional deployment served this login (e.g. `eu-west-1`). */
  serving_region?: string;
  /** Server-side session handle for logout calls. */
  session_id: string;
  /** OpenID Connect Session Management 1.0 §2 `session_state` — present */
  session_state?: string;
  token_strategy?: "jwt" | "session";
  token_type: string;
}

export interface LogoutRequest {
  session_id?: string;
}

export interface MFACompleteRequest {
  /** WebAuthn signed-assertion JSON (the response body */
  assertion?: string;
  /** TOTP code (RFC 6238) for the `totp` method. Six digits. */
  code?: string;
  /** The opaque challenge id returned by `/auth/login` in the */
  mfa_challenge_id: string;
  /** One of the values from the `mfa_methods` array the */
  mfa_method: string;
  /** Method-specific parameter map. When Params is set it wins */
  params?: Record<string, string>;
  /** When true AND a `TrustedDeviceStore` is wired, a SUCCESSFUL */
  trust_device?: boolean;
}

export interface MFARequiredResponse {
  /** Sentinel value. Use this to branch — the rest of the */
  error: "mfa_required";
  /** RFC 9207 authorization-response issuer identifier. */
  iss: string;
  /** Opaque challenge id to pass back on `POST /auth/mfa`. */
  mfa_challenge_id: string;
  /** Per-method server-issued challenge data for factors needing */
  mfa_method_data?: Record<string, Record<string, string>>;
  /** Factor names the wired MFAProvider can verify. SPAs render */
  mfa_methods: string[];
  /** Round-tripped from the original `/auth/login` request when set. */
  state?: string;
}

export interface MenuItem {
  buttons?: Button[];
  children?: MenuItem[];
  icon?: string;
  id: string;
  name: string;
  path?: string;
  permission?: string;
}

export type MenuTree = MenuItem[];

export interface MenuTreeResponse {
  client_id: string;
  menus: MenuTree;
}

/** OpenID Connect Discovery 1.0 + RFC 8414 metadata. Field set */
export interface OpenIDConfiguration {
  acr_values_supported?: string[];
  authorization_endpoint: string;
  /** RFC 9207. Always true on this server. */
  authorization_response_iss_parameter_supported?: boolean;
  backchannel_logout_session_supported?: boolean;
  backchannel_logout_supported?: boolean;
  /** OpenID Connect Session Management 1.0 §3. Present only when */
  check_session_iframe?: string;
  code_challenge_methods_supported?: string[];
  /** RFC 8628. Present only when a DeviceCodeStore is wired. */
  device_authorization_endpoint?: string;
  dpop_signing_alg_values_supported?: string[];
  /** OIDC RP-Initiated Logout 1.0. */
  end_session_endpoint?: string;
  frontchannel_logout_session_supported?: boolean;
  frontchannel_logout_supported?: boolean;
  grant_types_supported?: string[];
  /** Present only when a JWE response encrypter is wired (WithJWEResponseEncrypter). */
  id_token_encryption_alg_values_supported?: string[];
  /** Present only when a JWE response encrypter is wired. */
  id_token_encryption_enc_values_supported?: string[];
  id_token_signing_alg_values_supported: string[];
  introspection_endpoint?: string;
  /** RFC 9701 §7. Present ONLY when a dedicated introspection */
  introspection_signing_alg_values_supported?: string[];
  /** Identifier the AS uses for itself. MUST equal the */
  issuer: string;
  jwks_uri: string;
  mtls_endpoint_aliases?: Record<string, string>;
  /** RFC 9126. Present only when a PARStore is wired. */
  pushed_authorization_request_endpoint?: string;
  /** RFC 7591 DCR endpoint. Present only when DCR is enabled. */
  registration_endpoint?: string;
  require_pushed_authorization_requests?: boolean;
  response_modes_supported?: string[];
  response_types_supported: string[];
  revocation_endpoint?: string;
  scopes_supported?: string[];
  /** RFC 8414 §2.1 signed_metadata JWT. Present only when */
  signed_metadata?: string;
  subject_types_supported: "public" | "pairwise"[];
  tls_client_certificate_bound_access_tokens?: boolean;
  token_endpoint: string;
  token_endpoint_auth_methods_supported?: string[];
  /** Present only when a JWE response encrypter is wired. */
  userinfo_encryption_alg_values_supported?: string[];
  /** Present only when a JWE response encrypter is wired. */
  userinfo_encryption_enc_values_supported?: string[];
  userinfo_endpoint?: string;
  userinfo_signing_alg_values_supported?: string[];
}

export interface PARRequest {
  acr_values?: string;
  /** RFC 9396 Rich Authorization Requests. JSON body delivers */
  authorization_details?: AuthorizationDetail[];
  /** OIDC Core §5.5 claims request. */
  claims?: Record<string, unknown>;
  client_assertion?: string;
  client_assertion_type?: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer" | "urn:snaplink:params:oauth:client-assertion-type:workload-identity";
  client_id: string;
  client_secret?: string;
  /** RFC 7636 PKCE. */
  code_challenge?: string;
  code_challenge_method?: "S256" | "plain";
  login_hint?: string;
  /** OIDC nonce binding (Core §3.1.2.1). */
  nonce?: string;
  redirect_uri?: string;
  resource?: string[];
  /** OIDC Core response mode. The jwt / query.jwt / fragment.jwt / form_post.jwt values select JWT Secured Authorization Response Mode (JARM) and are only accepted when a JARM signer is wired (otherwise invalid_request). */
  response_mode?: "query" | "fragment" | "form_post" | "jwt" | "query.jwt" | "fragment.jwt" | "form_post.jwt";
  response_type?: "code";
  /** Space-delimited scope list. */
  scope?: string;
  /** Opaque CSRF token the RP later checks against the */
  state?: string;
  ui_locales?: string;
}

export interface PARResponse {
  /** Seconds until the request_uri is consumed or expires. */
  expires_in: number;
  request_uri: string;
}

export interface PaginatedLocalUsersResponse {
  limit: number;
  page: number;
  total: number;
  users: LocalUserResponse[];
}

export interface Permission {
  code: string;
  description?: string;
  name?: string;
}

export interface PermissionListResponse {
  client_id: string;
  permissions: Permission[];
}

export interface RevokeRequest {
  client_id?: string;
  client_secret?: string;
  /** The token to revoke. */
  token: string;
  token_type_hint?: "access_token" | "refresh_token";
}

export interface Role {
  code: string;
  /** Human-readable role description; surfaced on the admin */
  description?: string;
  name?: string;
  permissions?: string[];
}

export interface RoleListResponse {
  client_id: string;
  roles: Role[];
}

export interface SendCodeRequest {
  provider: "phone" | "email" | "magiclink";
  /** Phone number (E.164) or email address. `magiclink` also takes an */
  target: string;
}

export interface Session {
  created_at_unix?: number;
  expires_at_unix?: number;
  id?: string;
  /** Device/location context captured at session creation (best-effort; honors the first-hop X-Forwarded-For trust model). Omitted when not captured. */
  ip?: string;
  revoked?: boolean;
  /** User-Agent captured at session creation (best-effort). Omitted when not captured. */
  user_agent?: string;
  user_id?: string;
}

export interface TokenIssuance {
  access_token: string;
  /** OpenID Connect Native SSO 1.0: present when the client requested the */
  device_secret?: string;
  /** Access-token lifetime in seconds. */
  expires_in: number;
  /** Present when the client requested `openid` scope and */
  id_token?: string;
  /** RFC 8693 §2.2.1 — present on token-exchange responses. */
  issued_token_type?: "urn:ietf:params:oauth:token-type:access_token" | "urn:ietf:params:oauth:token-type:refresh_token" | "urn:ietf:params:oauth:token-type:txn-token";
  /** Present when a refresh token was issued. Family-rotated */
  refresh_token?: string;
  /** Space-delimited granted scopes. */
  scope?: string;
  /** `Bearer` for the legacy path; `DPoP` when the issuance */
  token_type: "Bearer" | "DPoP" | "N_A";
}

export interface TokenRequest {
  /** Space-delimited ACR list. On exchange, the dispatcher */
  acr_values?: string;
  /** RFC 8693 actor_token for delegation / impersonation. When */
  actor_token?: string;
  /** RFC 8693 token-type URI for the actor token. */
  actor_token_type?: "urn:ietf:params:oauth:token-type:access_token" | "urn:ietf:params:oauth:token-type:jwt" | "urn:openid:params:token-type:device-secret";
  /** For `grant_type=urn:snaplink:params:oauth:grant-type:delegation` */
  agent_session_id?: string;
  /** RFC 8693 audience list. Merged with `resource` (RFC 8707) */
  audience?: string[];
  /** RFC 7521 + 7523 JWT bearer client authentication. Signed */
  client_assertion?: string;
  /** MUST be the jwt-bearer URN, or the workload-identity URN */
  client_assertion_type?: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer" | "urn:snaplink:params:oauth:client-assertion-type:workload-identity";
  /** Public client identifier. Overridden by HTTP Basic */
  client_id?: string;
  /** Confidential client secret. Body form discouraged in */
  client_secret?: string;
  /** Authorization code for `grant_type=authorization_code`. */
  code?: string;
  /** RFC 7636 §4.5 PKCE verifier. Required when /auth/login */
  code_verifier?: string;
  /** For `grant_type=urn:ietf:params:oauth:grant-type:device_code`. */
  device_code?: string;
  /** Selects the grant branch. See the endpoint description */
  grant_type: "authorization_code" | "refresh_token" | "client_credentials" | "urn:ietf:params:oauth:grant-type:device_code" | "urn:ietf:params:oauth:grant-type:token-exchange" | "urn:snaplink:params:oauth:grant-type:delegation";
  /** RFC 9321 Transaction Tokens — the caller-supplied purpose */
  purp?: string;
  /** MUST equal the `redirect_uri` registered at /auth/login */
  redirect_uri?: string;
  /** For `grant_type=refresh_token`. */
  refresh_token?: string;
  /** RFC 9321 Transaction Tokens — an OPTIONAL caller-supplied */
  request_context?: string;
  /** RFC 8693 §2.1 — the token type the caller wants minted. */
  requested_token_type?: "urn:ietf:params:oauth:token-type:access_token" | "urn:ietf:params:oauth:token-type:refresh_token" | "urn:ietf:params:oauth:token-type:txn-token";
  /** RFC 8707 resource indicators. Repeat the form key for */
  resource?: string[];
  /** Space-delimited scope request. */
  scope?: string;
  /** RFC 8693 subject_token — the token being exchanged. The */
  subject_token?: string;
  /** RFC 8693 §3 token-type URI naming the subject_token's */
  subject_token_type?: "urn:ietf:params:oauth:token-type:access_token" | "urn:ietf:params:oauth:token-type:refresh_token" | "urn:ietf:params:oauth:token-type:id_token" | "urn:ietf:params:oauth:token-type:jwt" | "urn:ietf:params:oauth:token-type:txn-token";
}

export interface User {
  attributes?: Record<string, string>;
  created_at?: string;
  email?: string;
  external_id?: string;
  id: string;
  name?: string;
  provider?: string;
  updated_at?: string;
}

/** OIDC Core UserInfo claim projection for an openid-scoped bearer. */
export interface UserInfo {
  acr?: string;
  address?: string | Record<string, unknown>;
  amr?: string[];
  auth_time?: number;
  birthdate?: string;
  email?: string;
  email_verified?: boolean;
  family_name?: string;
  gender?: string;
  given_name?: string;
  locale?: string;
  name?: string;
  nickname?: string;
  phone_number?: string;
  phone_number_verified?: boolean;
  picture?: string;
  preferred_username?: string;
  profile?: string;
  sub: string;
  updated_at?: number;
  website?: string;
  zoneinfo?: string;
}

export class SSOClient {
  private readonly baseUrl: string;
  private readonly clientId: string | undefined;
  private readonly clientSecret: string | undefined;
  private readonly requestTimeoutMs: number | undefined;
  private readonly fetchImpl: FetchLike;
  private readonly getAccessToken: (() => string | undefined | Promise<string | undefined>) | undefined;
  /** Access token captured by login(); auto-attached to auth-required calls. */
  private token: string | undefined;

  constructor(opts: SSOClientOptions) {
    this.baseUrl = opts.baseUrl.replace(/\/+$/, "");
    this.clientId = opts.clientId;
    this.clientSecret = opts.clientSecret;
    if (opts.requestTimeoutMs !== undefined && (!Number.isFinite(opts.requestTimeoutMs) || opts.requestTimeoutMs <= 0)) {
      throw new SSOError(0, "invalid_request", "requestTimeoutMs must be a positive finite number");
    }
    this.requestTimeoutMs = opts.requestTimeoutMs;
    this.fetchImpl = opts.fetch ?? fetch;
    // Default token source is the token login() captured, so getUserInfo() etc.
    // work right after login without wiring anything.
    this.getAccessToken = opts.getAccessToken ?? (() => this.token);
  }

  /** True once login() succeeded and a token is held. */
  get isLoggedIn(): boolean {
    return !!this.token;
  }

  /** The access token captured by login() (undefined before login/after logout). */
  get accessToken(): string | undefined {
    return this.token;
  }

  /**
   * Password login: fills in the configured client_id and returns the auth
   * info (access_token / id_token / refresh_token / ...) directly — no redirect.
   * The token is captured internally so subsequent getUserInfo()/getMe() calls
   * auto-attach it. This is the simplest integration:
   *
   *   const sso = new SSOClient({ baseUrl, clientId: "my-app" });
   *   const auth = await sso.login(username, password);
   *   const me = await sso.getUserInfo();
   *
   * CHECK isLoggedIn (or "access_token" in auth) before assuming success: when
   * the account/client has MFA enabled, this resolves to a MFARequiredResponse
   * instead — no token is issued until POST /auth/mfa completes the second leg.
   */
  async login(
    username: string,
    password: string,
    opts?: { clientId?: string; scope?: string[]; extraCredential?: Record<string, string> },
  ): Promise<LoginResponse | MFARequiredResponse> {
    const clientId = opts?.clientId ?? this.clientId;
    if (!clientId) {
      throw new SSOError(0, "invalid_request", "clientId is required (set it in the constructor or pass it to login)");
    }
    // provider is always set below, so postLogin's LoginDiscoveryResponse (the
    // no-provider home-realm-discovery arm) can never apply to this call.
    const resp = (await this.postLogin({
      provider: "password",
      client_id: clientId,
      scope: opts?.scope ?? ["openid", "profile", "email"],
      credential: { username, password, ...(opts?.extraCredential ?? {}) },
    })) as LoginResponse | MFARequiredResponse;
    if ("access_token" in resp) this.token = resp.access_token;
    return resp;
  }

  /** Clear the held token and best-effort revoke the server session. */
  async logout(): Promise<void> {
    try {
      if (this.token) await this.postLogout({});
    } finally {
      this.token = undefined;
    }
  }

  private async request<T>(method: string, path: string, opts: requestOptions = {}): Promise<T> {
    let url = this.baseUrl + path;
    if (opts.query) {
      const qs = new URLSearchParams();
      for (const [k, v] of Object.entries(opts.query)) {
        if (v !== undefined) qs.set(k, String(v));
      }
      const s = qs.toString();
      if (s) url += "?" + s;
    }
    const headers: Record<string, string> = { Accept: "application/json" };
    const authenticatedBody = opts.clientAuth ? this.withClientAuthentication(opts.body, headers) : opts.body;
    const init: RequestInit = { method, headers };
    if (this.requestTimeoutMs !== undefined) init.signal = AbortSignal.timeout(this.requestTimeoutMs);
    if (authenticatedBody !== undefined) {
      headers["Content-Type"] = "application/json";
      init.body = JSON.stringify(authenticatedBody);
    }
    if (opts.auth && this.getAccessToken) {
      const token = await this.getAccessToken();
      if (token) headers["Authorization"] = `Bearer ${token}`;
    }
    const res = await this.fetchImpl(url, init);
    if (!res.ok) {
      let error: string | undefined;
      let errorDescription: string | undefined;
      try {
        const parsed = await res.json();
        error = parsed?.error;
        errorDescription = parsed?.error_description;
      } catch {
        // non-JSON error body; SSOError falls back to a generic message.
      }
      throw new SSOError(res.status, error, errorDescription);
    }
    if (res.status === 204) return undefined as T;
    const text = await res.text();
    return (text ? JSON.parse(text) : undefined) as T;
  }

  private withClientAuthentication(body: unknown, headers: Record<string, string>): unknown {
    if (!isRecord(body)) return body;
    const clientId = this.clientId ?? stringValue(body.client_id);
    const clientSecret = this.clientSecret ?? stringValue(body.client_secret);
    if (!clientSecret) return body;
    if (!clientId) {
      throw new SSOError(0, "invalid_request", "clientId is required when a confidential client secret is configured");
    }
    headers["Authorization"] = "Basic " + encodeBasicCredentials(clientId, clientSecret);
    const withoutCredentials = { ...body };
    delete withoutCredentials.client_id;
    delete withoutCredentials.client_secret;
    return withoutCredentials;
  }
  // ---- admin ----

  /** Runtime endpoint inventory — every route this replica actually registered. */
  async getAdminEndpoints(): Promise<{ endpoints?: { feature?: string; method?: string; path?: string }[]; status?: string }> {
    return this.request<{ endpoints?: { feature?: string; method?: string; path?: string }[]; status?: string }>("GET", `/api/v1/admin/endpoints`, { auth: true });
  }

  /** List LOCAL (password-authenticated) users. */
  async adminLocalUserList(query?: { page?: number; limit?: number }): Promise<PaginatedLocalUsersResponse> {
    return this.request<PaginatedLocalUsersResponse>("GET", `/api/v1/admin/local-users`, { query: { "page": query?.page, "limit": query?.limit }, auth: true });
  }

  /** List roles for a client. */
  async permissionListRoles(clientId: string, query?: { pageSize?: number; pageToken?: string }): Promise<ListRolesResponse> {
    return this.request<ListRolesResponse>("GET", `/api/v1/admin/permissions/${encodeURIComponent(clientId)}/roles`, { query: { "page_size": query?.pageSize, "page_token": query?.pageToken }, auth: true });
  }

  /** Query audit events. */
  async queryAuditEvents(query?: { type?: string; actorId?: string; clientId?: string; tenantId?: string; provider?: string; outcome?: "success" | "failure"; requestId?: string; traceId?: string; since?: string; until?: string; limit?: number; offset?: number }): Promise<AuditEventList> {
    return this.request<AuditEventList>("GET", `/api/v1/audit/events`, { query: { "type": query?.type, "actor_id": query?.actorId, "client_id": query?.clientId, "tenant_id": query?.tenantId, "provider": query?.provider, "outcome": query?.outcome, "request_id": query?.requestId, "trace_id": query?.traceId, "since": query?.since, "until": query?.until, "limit": query?.limit, "offset": query?.offset }, auth: true });
  }

  /** Fetch one Client record. */
  async getClientByID(id: string): Promise<ClientMetadata> {
    return this.request<ClientMetadata>("GET", `/api/v1/clients/${encodeURIComponent(id)}`, {});
  }

  // ---- auth ----

  /** Authenticate and receive a token. */
  async postLogin(body: LoginRequest): Promise<LoginResponse | AuthorizationCodeResponse | LoginDiscoveryResponse | MFARequiredResponse> {
    return this.request<LoginResponse | AuthorizationCodeResponse | LoginDiscoveryResponse | MFARequiredResponse>("POST", `/auth/login`, { body });
  }

  /** Complete an MFA step-up challenge. */
  async postMFAComplete(body: MFACompleteRequest): Promise<LoginResponse | AuthorizationCodeResponse> {
    return this.request<LoginResponse | AuthorizationCodeResponse>("POST", `/auth/mfa`, { body });
  }

  /** Send a one-time code for the named authenticator. */
  async postSendCode(body: SendCodeRequest): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>("POST", `/auth/send-code`, { body });
  }

  /** Device-flow initiation (RFC 8628 §3.1). */
  async postDeviceCode(body: DeviceCodeRequest): Promise<DeviceCodeResponse> {
    return this.request<DeviceCodeResponse>("POST", `/device/code`, { body });
  }

  /** User-side device-code approval (RFC 8628 §3.3). */
  async postDeviceVerify(body: DeviceVerifyRequest): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>("POST", `/device/verify`, { body, auth: true });
  }

  /** Revoke the current bearer token and / or named session. */
  async postLogout(body?: LogoutRequest): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>("POST", `/logout`, { body, auth: true });
  }

  /** Pushed Authorization Request (RFC 9126). */
  async postPAR(body: PARRequest): Promise<PARResponse> {
    return this.request<PARResponse>("POST", `/par`, { body, clientAuth: true });
  }

  /** Dynamic Client Registration (RFC 7591). */
  async postRegister(body: DCRRequest): Promise<DCRResponse> {
    return this.request<DCRResponse>("POST", `/register`, { body, auth: true });
  }

  /** Deregister the client (RFC 7592 §2.3). */
  async deleteRegistration(clientId: string): Promise<void> {
    return this.request<void>("DELETE", `/register/${encodeURIComponent(clientId)}`, { auth: true });
  }

  /** Read current DCR metadata (RFC 7592 §2.1). */
  async getRegistration(clientId: string): Promise<DCRResponse> {
    return this.request<DCRResponse>("GET", `/register/${encodeURIComponent(clientId)}`, { auth: true });
  }

  /** Update DCR metadata (RFC 7592 §2.2). */
  async putRegistration(clientId: string, body: DCRRequest): Promise<DCRResponse> {
    return this.request<DCRResponse>("PUT", `/register/${encodeURIComponent(clientId)}`, { body, auth: true });
  }

  /** OAuth 2.0 token endpoint (RFC 6749 §3.2). */
  async postToken(body: TokenRequest): Promise<TokenIssuance> {
    return this.request<TokenIssuance>("POST", `/token`, { body, clientAuth: true });
  }

  /** OAuth 2.0 token introspection (RFC 7662). */
  async postIntrospect(body: IntrospectRequest): Promise<IntrospectResponse | IntrospectBatchResponse> {
    return this.request<IntrospectResponse | IntrospectBatchResponse>("POST", `/token/introspect`, { body, clientAuth: true });
  }

  /** OAuth 2.0 token revocation (RFC 7009). */
  async postRevoke(body: RevokeRequest): Promise<void> {
    return this.request<void>("POST", `/token/revoke`, { body, clientAuth: true });
  }

  /** Bulk revoke every refresh token bound to the bearer's subject. */
  async postRevokeAll(): Promise<{ refresh_tokens_revoked?: number; status?: string; trusted_devices_revoked?: number }> {
    return this.request<{ refresh_tokens_revoked?: number; status?: string; trusted_devices_revoked?: number }>("POST", `/token/revoke-all`, { auth: true });
  }

  // ---- discovery ----

  /** JSON Web Key Set for local JWT verification. */
  async getJWKS(): Promise<JWKS> {
    return this.request<JWKS>("GET", `/.well-known/jwks.json`, {});
  }

  /** RFC 8414 OAuth 2.0 Authorization Server Metadata (alias). */
  async getOAuthAuthorizationServerMetadata(): Promise<OpenIDConfiguration> {
    return this.request<OpenIDConfiguration>("GET", `/.well-known/oauth-authorization-server`, {});
  }

  /** OpenID Connect Discovery 1.0 document. */
  async getOpenIDConfiguration(): Promise<OpenIDConfiguration> {
    return this.request<OpenIDConfiguration>("GET", `/.well-known/openid-configuration`, {});
  }

  // ---- me ----

  /** Menu tree the bearer's subject is authorized to see. */
  async getMyMenus(query?: { clientId?: string }): Promise<MenuTreeResponse> {
    return this.request<MenuTreeResponse>("GET", `/menus/me`, { query: { "client_id": query?.clientId }, auth: true });
  }

  /** Permissions of the bearer's subject for the inferred client. */
  async getMyPermissions(query?: { clientId?: string }): Promise<PermissionListResponse> {
    return this.request<PermissionListResponse>("GET", `/permissions/me`, { query: { "client_id": query?.clientId }, auth: true });
  }

  /** Roles of the bearer's subject for the inferred client. */
  async getMyRoles(query?: { clientId?: string }): Promise<RoleListResponse> {
    return this.request<RoleListResponse>("GET", `/roles/me`, { query: { "client_id": query?.clientId }, auth: true });
  }

  // ---- self-service ----

  /** List the authenticated user's consent grants. */
  async listMyConsents(): Promise<{ consents?: { client_id?: string; granted_at?: string; scopes?: string[]; user_id?: string }[] }> {
    return this.request<{ consents?: { client_id?: string; granted_at?: string; scopes?: string[]; user_id?: string }[] }>("GET", `/consents/me`, { auth: true });
  }

  /** Authenticated self-service account overview. */
  async getMe(): Promise<{ active_sessions?: number; granted_apps?: number; iss?: string; sub?: string; user?: User }> {
    return this.request<{ active_sessions?: number; granted_apps?: number; iss?: string; sub?: string; user?: User }>("GET", `/me`, { auth: true });
  }

  /** Authenticated self-service profile update. */
  async patchMe(body: { attributes?: Record<string, string>; name?: string }): Promise<{ iss?: string; user?: User }> {
    return this.request<{ iss?: string; user?: User }>("PATCH", `/me`, { body, auth: true });
  }

  /** List the authenticated user's registered second factors. */
  async listMyMFAFactors(): Promise<{ factors?: { added_at?: string; discoverable?: boolean; id?: string; label?: string; method?: string }[] }> {
    return this.request<{ factors?: { added_at?: string; discoverable?: boolean; id?: string; label?: string; method?: string }[] }>("GET", `/me/mfa`, { auth: true });
  }

  /** Authenticated self-service password change. */
  async changeMyPassword(body: { current_password: string; new_password: string }): Promise<void> {
    return this.request<void>("POST", `/me/password`, { body, auth: true });
  }

  /** Sign out everywhere — revoke the user's sessions in bulk. */
  async revokeMySessions(query?: { all?: boolean }): Promise<{ revoked?: number }> {
    return this.request<{ revoked?: number }>("DELETE", `/sessions/me`, { query: { "all": query?.all }, auth: true });
  }

  /** List the authenticated user's own active sessions. */
  async listMySessions(): Promise<{ sessions?: Session[] }> {
    return this.request<{ sessions?: Session[] }>("GET", `/sessions/me`, { auth: true });
  }

  // ---- userinfo ----

  /** Fetch the user record for the bearer's subject. */
  async getUserInfo(): Promise<UserInfo> {
    return this.request<UserInfo>("GET", `/userinfo`, { auth: true });
  }

}
