// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: admin/v1/releases.proto

// Package admin/v1 — STABLE.
// See docs/adr/ADR-0008-proto-versioning.md for the versioning policy.
// Breaking changes are not permitted in this package without a minimum
// 6-month deprecation window.

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReleaseAdminService_Register_FullMethodName   = "/snaplink.admin.v1.ReleaseAdminService/Register"
	ReleaseAdminService_List_FullMethodName       = "/snaplink.admin.v1.ReleaseAdminService/List"
	ReleaseAdminService_Get_FullMethodName        = "/snaplink.admin.v1.ReleaseAdminService/Get"
	ReleaseAdminService_GetCurrent_FullMethodName = "/snaplink.admin.v1.ReleaseAdminService/GetCurrent"
	ReleaseAdminService_Pin_FullMethodName        = "/snaplink.admin.v1.ReleaseAdminService/Pin"
	ReleaseAdminService_Rollback_FullMethodName   = "/snaplink.admin.v1.ReleaseAdminService/Rollback"
	ReleaseAdminService_Delete_FullMethodName     = "/snaplink.admin.v1.ReleaseAdminService/Delete"
)

// ReleaseAdminServiceClient is the client API for ReleaseAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReleaseAdminService manages paired frontend+backend release
// artifacts (Phase D-3). Pin marks one as current; Rollback flips to
// a previous one with reversed Pinner ordering. Every mutation
// requires the admin:* scope and writes one audit event.
type ReleaseAdminServiceClient interface {
	Register(ctx context.Context, in *RegisterReleaseRequest, opts ...grpc.CallOption) (*RegisterReleaseResponse, error)
	List(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*ListReleasesResponse, error)
	Get(ctx context.Context, in *GetReleaseRequest, opts ...grpc.CallOption) (*GetReleaseResponse, error)
	GetCurrent(ctx context.Context, in *GetCurrentReleaseRequest, opts ...grpc.CallOption) (*GetCurrentReleaseResponse, error)
	Pin(ctx context.Context, in *PinReleaseRequest, opts ...grpc.CallOption) (*PinReleaseResponse, error)
	Rollback(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error)
	Delete(ctx context.Context, in *DeleteReleaseRequest, opts ...grpc.CallOption) (*DeleteReleaseResponse, error)
}

type releaseAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReleaseAdminServiceClient(cc grpc.ClientConnInterface) ReleaseAdminServiceClient {
	return &releaseAdminServiceClient{cc}
}

func (c *releaseAdminServiceClient) Register(ctx context.Context, in *RegisterReleaseRequest, opts ...grpc.CallOption) (*RegisterReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterReleaseResponse)
	err := c.cc.Invoke(ctx, ReleaseAdminService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseAdminServiceClient) List(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*ListReleasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReleasesResponse)
	err := c.cc.Invoke(ctx, ReleaseAdminService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseAdminServiceClient) Get(ctx context.Context, in *GetReleaseRequest, opts ...grpc.CallOption) (*GetReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReleaseResponse)
	err := c.cc.Invoke(ctx, ReleaseAdminService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseAdminServiceClient) GetCurrent(ctx context.Context, in *GetCurrentReleaseRequest, opts ...grpc.CallOption) (*GetCurrentReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentReleaseResponse)
	err := c.cc.Invoke(ctx, ReleaseAdminService_GetCurrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseAdminServiceClient) Pin(ctx context.Context, in *PinReleaseRequest, opts ...grpc.CallOption) (*PinReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PinReleaseResponse)
	err := c.cc.Invoke(ctx, ReleaseAdminService_Pin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseAdminServiceClient) Rollback(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackReleaseResponse)
	err := c.cc.Invoke(ctx, ReleaseAdminService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseAdminServiceClient) Delete(ctx context.Context, in *DeleteReleaseRequest, opts ...grpc.CallOption) (*DeleteReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReleaseResponse)
	err := c.cc.Invoke(ctx, ReleaseAdminService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReleaseAdminServiceServer is the server API for ReleaseAdminService service.
// All implementations must embed UnimplementedReleaseAdminServiceServer
// for forward compatibility.
//
// ReleaseAdminService manages paired frontend+backend release
// artifacts (Phase D-3). Pin marks one as current; Rollback flips to
// a previous one with reversed Pinner ordering. Every mutation
// requires the admin:* scope and writes one audit event.
type ReleaseAdminServiceServer interface {
	Register(context.Context, *RegisterReleaseRequest) (*RegisterReleaseResponse, error)
	List(context.Context, *ListReleasesRequest) (*ListReleasesResponse, error)
	Get(context.Context, *GetReleaseRequest) (*GetReleaseResponse, error)
	GetCurrent(context.Context, *GetCurrentReleaseRequest) (*GetCurrentReleaseResponse, error)
	Pin(context.Context, *PinReleaseRequest) (*PinReleaseResponse, error)
	Rollback(context.Context, *RollbackReleaseRequest) (*RollbackReleaseResponse, error)
	Delete(context.Context, *DeleteReleaseRequest) (*DeleteReleaseResponse, error)
	mustEmbedUnimplementedReleaseAdminServiceServer()
}

// UnimplementedReleaseAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReleaseAdminServiceServer struct{}

func (UnimplementedReleaseAdminServiceServer) Register(context.Context, *RegisterReleaseRequest) (*RegisterReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedReleaseAdminServiceServer) List(context.Context, *ListReleasesRequest) (*ListReleasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedReleaseAdminServiceServer) Get(context.Context, *GetReleaseRequest) (*GetReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedReleaseAdminServiceServer) GetCurrent(context.Context, *GetCurrentReleaseRequest) (*GetCurrentReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrent not implemented")
}
func (UnimplementedReleaseAdminServiceServer) Pin(context.Context, *PinReleaseRequest) (*PinReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pin not implemented")
}
func (UnimplementedReleaseAdminServiceServer) Rollback(context.Context, *RollbackReleaseRequest) (*RollbackReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedReleaseAdminServiceServer) Delete(context.Context, *DeleteReleaseRequest) (*DeleteReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedReleaseAdminServiceServer) mustEmbedUnimplementedReleaseAdminServiceServer() {}
func (UnimplementedReleaseAdminServiceServer) testEmbeddedByValue()                             {}

// UnsafeReleaseAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReleaseAdminServiceServer will
// result in compilation errors.
type UnsafeReleaseAdminServiceServer interface {
	mustEmbedUnimplementedReleaseAdminServiceServer()
}

func RegisterReleaseAdminServiceServer(s grpc.ServiceRegistrar, srv ReleaseAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedReleaseAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReleaseAdminService_ServiceDesc, srv)
}

func _ReleaseAdminService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseAdminServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseAdminService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseAdminServiceServer).Register(ctx, req.(*RegisterReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseAdminService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReleasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseAdminServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseAdminService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseAdminServiceServer).List(ctx, req.(*ListReleasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseAdminService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseAdminServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseAdminService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseAdminServiceServer).Get(ctx, req.(*GetReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseAdminService_GetCurrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseAdminServiceServer).GetCurrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseAdminService_GetCurrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseAdminServiceServer).GetCurrent(ctx, req.(*GetCurrentReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseAdminService_Pin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseAdminServiceServer).Pin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseAdminService_Pin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseAdminServiceServer).Pin(ctx, req.(*PinReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseAdminService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseAdminServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseAdminService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseAdminServiceServer).Rollback(ctx, req.(*RollbackReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseAdminService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseAdminServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReleaseAdminService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseAdminServiceServer).Delete(ctx, req.(*DeleteReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReleaseAdminService_ServiceDesc is the grpc.ServiceDesc for ReleaseAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReleaseAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snaplink.admin.v1.ReleaseAdminService",
	HandlerType: (*ReleaseAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ReleaseAdminService_Register_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ReleaseAdminService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ReleaseAdminService_Get_Handler,
		},
		{
			MethodName: "GetCurrent",
			Handler:    _ReleaseAdminService_GetCurrent_Handler,
		},
		{
			MethodName: "Pin",
			Handler:    _ReleaseAdminService_Pin_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _ReleaseAdminService_Rollback_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ReleaseAdminService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/releases.proto",
}
