// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: admin/v1/snapshots.proto

// Package admin/v1 — STABLE.
// See docs/adr/ADR-0008-proto-versioning.md for the versioning policy.
// Breaking changes are not permitted in this package without a minimum
// 6-month deprecation window.

package adminv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Categories to omit from the export. Empty = include every wired
	// backend's data.
	Exclude []string `protobuf:"bytes,1,rep,name=exclude,proto3" json:"exclude,omitempty"`
	// Optional human-readable node identifier stamped onto the snapshot.
	// Useful when the same operator runs Export across many nodes.
	SourceNodeId  string `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSnapshotRequest) Reset() {
	*x = ExportSnapshotRequest{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSnapshotRequest) ProtoMessage() {}

func (x *ExportSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ExportSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *ExportSnapshotRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *ExportSnapshotRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

type ExportSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The exported snapshot envelope (header + counts; body resources
	// omitted from the wire response — fetch the full body via Get).
	Meta *SnapshotMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Storage key the snapshot was persisted under. Equal to
	// meta.snapshot_id today; reserved as a separate field so future
	// backends with translation layers can return e.g. an S3 object key.
	StoredAs      string `protobuf:"bytes,2,opt,name=stored_as,json=storedAs,proto3" json:"stored_as,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSnapshotResponse) Reset() {
	*x = ExportSnapshotResponse{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSnapshotResponse) ProtoMessage() {}

func (x *ExportSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ExportSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *ExportSnapshotResponse) GetMeta() *SnapshotMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ExportSnapshotResponse) GetStoredAs() string {
	if x != nil {
		return x.StoredAs
	}
	return ""
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageToken     string                 `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{2}
}

func (x *ListSnapshotsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSnapshotsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int32                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Items         []*SnapshotMeta        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{3}
}

func (x *ListSnapshotsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListSnapshotsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListSnapshotsResponse) GetItems() []*SnapshotMeta {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{4}
}

func (x *GetSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *SnapshotMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// resources is the raw JSON body of snapshot.Snapshot.Resources,
	// returned as-is so admin UIs can render it without the server
	// having to mirror every SDK type into proto.
	ResourcesJson []byte `protobuf:"bytes,2,opt,name=resources_json,json=resourcesJson,proto3" json:"resources_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{5}
}

func (x *GetSnapshotResponse) GetMeta() *SnapshotMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetSnapshotResponse) GetResourcesJson() []byte {
	if x != nil {
		return x.ResourcesJson
	}
	return nil
}

type RestoreSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Mode: merge | overwrite | replace. Defaults to merge when empty.
	Mode             string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	DryRun           bool   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	AdvanceBootstrap bool   `protobuf:"varint,4,opt,name=advance_bootstrap,json=advanceBootstrap,proto3" json:"advance_bootstrap,omitempty"`
	// Confirm token — required iff mode = "replace"; must equal the
	// snapshot's own SnapshotID.
	Confirm       string   `protobuf:"bytes,5,opt,name=confirm,proto3" json:"confirm,omitempty"`
	Exclude       []string `protobuf:"bytes,6,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSnapshotRequest) Reset() {
	*x = RestoreSnapshotRequest{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSnapshotRequest) ProtoMessage() {}

func (x *RestoreSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RestoreSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestoreSnapshotRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RestoreSnapshotRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *RestoreSnapshotRequest) GetAdvanceBootstrap() bool {
	if x != nil {
		return x.AdvanceBootstrap
	}
	return false
}

func (x *RestoreSnapshotRequest) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

func (x *RestoreSnapshotRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type RestoreSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *RestoreReport         `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSnapshotResponse) Reset() {
	*x = RestoreSnapshotResponse{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSnapshotResponse) ProtoMessage() {}

func (x *RestoreSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RestoreSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreSnapshotResponse) GetReport() *RestoreReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{9}
}

// SnapshotMeta is the header projection of a Snapshot — enough for List
// rendering without forcing decryption. taken_at_unix is seconds since
// epoch.
type SnapshotMeta struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion       string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	SnapshotId          string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	TakenAtUnix         int64                  `protobuf:"varint,3,opt,name=taken_at_unix,json=takenAtUnix,proto3" json:"taken_at_unix,omitempty"`
	SourceNamespace     string                 `protobuf:"bytes,4,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	SourceNodeId        string                 `protobuf:"bytes,5,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	SizeBytes           int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Codec               string                 `protobuf:"bytes,7,opt,name=codec,proto3" json:"codec,omitempty"`
	EncryptionAlgorithm string                 `protobuf:"bytes,8,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3" json:"encryption_algorithm,omitempty"`
	// Bootstrap tracker high-water mark recorded in this snapshot's
	// namespace at the moment of export.
	BootstrapAppliedVersion int32 `protobuf:"varint,9,opt,name=bootstrap_applied_version,json=bootstrapAppliedVersion,proto3" json:"bootstrap_applied_version,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SnapshotMeta) Reset() {
	*x = SnapshotMeta{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMeta) ProtoMessage() {}

func (x *SnapshotMeta) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMeta.ProtoReflect.Descriptor instead.
func (*SnapshotMeta) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotMeta) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SnapshotMeta) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotMeta) GetTakenAtUnix() int64 {
	if x != nil {
		return x.TakenAtUnix
	}
	return 0
}

func (x *SnapshotMeta) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *SnapshotMeta) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *SnapshotMeta) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SnapshotMeta) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *SnapshotMeta) GetEncryptionAlgorithm() string {
	if x != nil {
		return x.EncryptionAlgorithm
	}
	return ""
}

func (x *SnapshotMeta) GetBootstrapAppliedVersion() int32 {
	if x != nil {
		return x.BootstrapAppliedVersion
	}
	return 0
}

// RestoreReport mirrors snapshot.Report. Counts roll up across resources.
type RestoreReport struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Mode          string                     `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	DryRun        bool                       `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Items         map[string]*CategoryCounts `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bootstrap     *BootstrapAdvance          `protobuf:"bytes,4,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	Errors        []string                   `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreReport) Reset() {
	*x = RestoreReport{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreReport) ProtoMessage() {}

func (x *RestoreReport) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreReport.ProtoReflect.Descriptor instead.
func (*RestoreReport) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{11}
}

func (x *RestoreReport) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RestoreReport) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *RestoreReport) GetItems() map[string]*CategoryCounts {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RestoreReport) GetBootstrap() *BootstrapAdvance {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

func (x *RestoreReport) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CategoryCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Updated       int32                  `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted       int32                  `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Skipped       int32                  `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryCounts) Reset() {
	*x = CategoryCounts{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCounts) ProtoMessage() {}

func (x *CategoryCounts) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCounts.ProtoReflect.Descriptor instead.
func (*CategoryCounts) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{12}
}

func (x *CategoryCounts) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *CategoryCounts) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *CategoryCounts) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *CategoryCounts) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

type BootstrapAdvance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempted     bool                   `protobuf:"varint,1,opt,name=attempted,proto3" json:"attempted,omitempty"`
	From          int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	NoOp          bool                   `protobuf:"varint,4,opt,name=no_op,json=noOp,proto3" json:"no_op,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapAdvance) Reset() {
	*x = BootstrapAdvance{}
	mi := &file_admin_v1_snapshots_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapAdvance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapAdvance) ProtoMessage() {}

func (x *BootstrapAdvance) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_snapshots_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapAdvance.ProtoReflect.Descriptor instead.
func (*BootstrapAdvance) Descriptor() ([]byte, []int) {
	return file_admin_v1_snapshots_proto_rawDescGZIP(), []int{13}
}

func (x *BootstrapAdvance) GetAttempted() bool {
	if x != nil {
		return x.Attempted
	}
	return false
}

func (x *BootstrapAdvance) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *BootstrapAdvance) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *BootstrapAdvance) GetNoOp() bool {
	if x != nil {
		return x.NoOp
	}
	return false
}

func (x *BootstrapAdvance) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_admin_v1_snapshots_proto protoreflect.FileDescriptor

const file_admin_v1_snapshots_proto_rawDesc = "" +
	"\n" +
	"\x18admin/v1/snapshots.proto\x12\x11snaplink.admin.v1\x1a\x1cgoogle/api/annotations.proto\"W\n" +
	"\x15ExportSnapshotRequest\x12\x18\n" +
	"\aexclude\x18\x01 \x03(\tR\aexclude\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\"j\n" +
	"\x16ExportSnapshotResponse\x123\n" +
	"\x04meta\x18\x01 \x01(\v2\x1f.snaplink.admin.v1.SnapshotMetaR\x04meta\x12\x1b\n" +
	"\tstored_as\x18\x02 \x01(\tR\bstoredAs\"R\n" +
	"\x14ListSnapshotsRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x95\x01\n" +
	"\x15ListSnapshotsResponse\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.snaplink.admin.v1.SnapshotMetaR\x05items\"$\n" +
	"\x12GetSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"q\n" +
	"\x13GetSnapshotResponse\x123\n" +
	"\x04meta\x18\x01 \x01(\v2\x1f.snaplink.admin.v1.SnapshotMetaR\x04meta\x12%\n" +
	"\x0eresources_json\x18\x02 \x01(\fR\rresourcesJson\"\xb6\x01\n" +
	"\x16RestoreSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x12+\n" +
	"\x11advance_bootstrap\x18\x04 \x01(\bR\x10advanceBootstrap\x12\x18\n" +
	"\aconfirm\x18\x05 \x01(\tR\aconfirm\x12\x18\n" +
	"\aexclude\x18\x06 \x03(\tR\aexclude\"S\n" +
	"\x17RestoreSnapshotResponse\x128\n" +
	"\x06report\x18\x01 \x01(\v2 .snaplink.admin.v1.RestoreReportR\x06report\"'\n" +
	"\x15DeleteSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteSnapshotResponse\"\xef\x02\n" +
	"\fSnapshotMeta\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\"\n" +
	"\rtaken_at_unix\x18\x03 \x01(\x03R\vtakenAtUnix\x12)\n" +
	"\x10source_namespace\x18\x04 \x01(\tR\x0fsourceNamespace\x12$\n" +
	"\x0esource_node_id\x18\x05 \x01(\tR\fsourceNodeId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05codec\x18\a \x01(\tR\x05codec\x121\n" +
	"\x14encryption_algorithm\x18\b \x01(\tR\x13encryptionAlgorithm\x12:\n" +
	"\x19bootstrap_applied_version\x18\t \x01(\x05R\x17bootstrapAppliedVersion\"\xb7\x02\n" +
	"\rRestoreReport\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\x12A\n" +
	"\x05items\x18\x03 \x03(\v2+.snaplink.admin.v1.RestoreReport.ItemsEntryR\x05items\x12A\n" +
	"\tbootstrap\x18\x04 \x01(\v2#.snaplink.admin.v1.BootstrapAdvanceR\tbootstrap\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\x1a[\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.snaplink.admin.v1.CategoryCountsR\x05value:\x028\x01\"z\n" +
	"\x0eCategoryCounts\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\x05R\aupdated\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\x05R\adeleted\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped\"\x81\x01\n" +
	"\x10BootstrapAdvance\x12\x1c\n" +
	"\tattempted\x18\x01 \x01(\bR\tattempted\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x05R\x02to\x12\x13\n" +
	"\x05no_op\x18\x04 \x01(\bR\x04noOp\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason2\xac\x05\n" +
	"\x14SnapshotAdminService\x12\x81\x01\n" +
	"\x06Export\x12(.snaplink.admin.v1.ExportSnapshotRequest\x1a).snaplink.admin.v1.ExportSnapshotResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/admin/snapshots\x12z\n" +
	"\x04List\x12'.snaplink.admin.v1.ListSnapshotsRequest\x1a(.snaplink.admin.v1.ListSnapshotsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/admin/snapshots\x12z\n" +
	"\x03Get\x12%.snaplink.admin.v1.GetSnapshotRequest\x1a&.snaplink.admin.v1.GetSnapshotResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/admin/snapshots/{id}\x12\x91\x01\n" +
	"\aRestore\x12).snaplink.admin.v1.RestoreSnapshotRequest\x1a*.snaplink.admin.v1.RestoreSnapshotResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/admin/snapshots/{id}:restore\x12\x83\x01\n" +
	"\x06Delete\x12(.snaplink.admin.v1.DeleteSnapshotRequest\x1a).snaplink.admin.v1.DeleteSnapshotResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/api/v1/admin/snapshots/{id}B4Z2github.com/snaplink/sso/gen/proto/admin/v1;adminv1b\x06proto3"

var (
	file_admin_v1_snapshots_proto_rawDescOnce sync.Once
	file_admin_v1_snapshots_proto_rawDescData []byte
)

func file_admin_v1_snapshots_proto_rawDescGZIP() []byte {
	file_admin_v1_snapshots_proto_rawDescOnce.Do(func() {
		file_admin_v1_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_snapshots_proto_rawDesc), len(file_admin_v1_snapshots_proto_rawDesc)))
	})
	return file_admin_v1_snapshots_proto_rawDescData
}

var file_admin_v1_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_admin_v1_snapshots_proto_goTypes = []any{
	(*ExportSnapshotRequest)(nil),   // 0: snaplink.admin.v1.ExportSnapshotRequest
	(*ExportSnapshotResponse)(nil),  // 1: snaplink.admin.v1.ExportSnapshotResponse
	(*ListSnapshotsRequest)(nil),    // 2: snaplink.admin.v1.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),   // 3: snaplink.admin.v1.ListSnapshotsResponse
	(*GetSnapshotRequest)(nil),      // 4: snaplink.admin.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),     // 5: snaplink.admin.v1.GetSnapshotResponse
	(*RestoreSnapshotRequest)(nil),  // 6: snaplink.admin.v1.RestoreSnapshotRequest
	(*RestoreSnapshotResponse)(nil), // 7: snaplink.admin.v1.RestoreSnapshotResponse
	(*DeleteSnapshotRequest)(nil),   // 8: snaplink.admin.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),  // 9: snaplink.admin.v1.DeleteSnapshotResponse
	(*SnapshotMeta)(nil),            // 10: snaplink.admin.v1.SnapshotMeta
	(*RestoreReport)(nil),           // 11: snaplink.admin.v1.RestoreReport
	(*CategoryCounts)(nil),          // 12: snaplink.admin.v1.CategoryCounts
	(*BootstrapAdvance)(nil),        // 13: snaplink.admin.v1.BootstrapAdvance
	nil,                             // 14: snaplink.admin.v1.RestoreReport.ItemsEntry
}
var file_admin_v1_snapshots_proto_depIdxs = []int32{
	10, // 0: snaplink.admin.v1.ExportSnapshotResponse.meta:type_name -> snaplink.admin.v1.SnapshotMeta
	10, // 1: snaplink.admin.v1.ListSnapshotsResponse.items:type_name -> snaplink.admin.v1.SnapshotMeta
	10, // 2: snaplink.admin.v1.GetSnapshotResponse.meta:type_name -> snaplink.admin.v1.SnapshotMeta
	11, // 3: snaplink.admin.v1.RestoreSnapshotResponse.report:type_name -> snaplink.admin.v1.RestoreReport
	14, // 4: snaplink.admin.v1.RestoreReport.items:type_name -> snaplink.admin.v1.RestoreReport.ItemsEntry
	13, // 5: snaplink.admin.v1.RestoreReport.bootstrap:type_name -> snaplink.admin.v1.BootstrapAdvance
	12, // 6: snaplink.admin.v1.RestoreReport.ItemsEntry.value:type_name -> snaplink.admin.v1.CategoryCounts
	0,  // 7: snaplink.admin.v1.SnapshotAdminService.Export:input_type -> snaplink.admin.v1.ExportSnapshotRequest
	2,  // 8: snaplink.admin.v1.SnapshotAdminService.List:input_type -> snaplink.admin.v1.ListSnapshotsRequest
	4,  // 9: snaplink.admin.v1.SnapshotAdminService.Get:input_type -> snaplink.admin.v1.GetSnapshotRequest
	6,  // 10: snaplink.admin.v1.SnapshotAdminService.Restore:input_type -> snaplink.admin.v1.RestoreSnapshotRequest
	8,  // 11: snaplink.admin.v1.SnapshotAdminService.Delete:input_type -> snaplink.admin.v1.DeleteSnapshotRequest
	1,  // 12: snaplink.admin.v1.SnapshotAdminService.Export:output_type -> snaplink.admin.v1.ExportSnapshotResponse
	3,  // 13: snaplink.admin.v1.SnapshotAdminService.List:output_type -> snaplink.admin.v1.ListSnapshotsResponse
	5,  // 14: snaplink.admin.v1.SnapshotAdminService.Get:output_type -> snaplink.admin.v1.GetSnapshotResponse
	7,  // 15: snaplink.admin.v1.SnapshotAdminService.Restore:output_type -> snaplink.admin.v1.RestoreSnapshotResponse
	9,  // 16: snaplink.admin.v1.SnapshotAdminService.Delete:output_type -> snaplink.admin.v1.DeleteSnapshotResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_admin_v1_snapshots_proto_init() }
func file_admin_v1_snapshots_proto_init() {
	if File_admin_v1_snapshots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_snapshots_proto_rawDesc), len(file_admin_v1_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_snapshots_proto_goTypes,
		DependencyIndexes: file_admin_v1_snapshots_proto_depIdxs,
		MessageInfos:      file_admin_v1_snapshots_proto_msgTypes,
	}.Build()
	File_admin_v1_snapshots_proto = out.File
	file_admin_v1_snapshots_proto_goTypes = nil
	file_admin_v1_snapshots_proto_depIdxs = nil
}
