// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: admin/v1/snapshots.proto

// Package admin/v1 — STABLE.
// See docs/adr/ADR-0008-proto-versioning.md for the versioning policy.
// Breaking changes are not permitted in this package without a minimum
// 6-month deprecation window.

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnapshotAdminService_Export_FullMethodName  = "/snaplink.admin.v1.SnapshotAdminService/Export"
	SnapshotAdminService_List_FullMethodName    = "/snaplink.admin.v1.SnapshotAdminService/List"
	SnapshotAdminService_Get_FullMethodName     = "/snaplink.admin.v1.SnapshotAdminService/Get"
	SnapshotAdminService_Restore_FullMethodName = "/snaplink.admin.v1.SnapshotAdminService/Restore"
	SnapshotAdminService_Delete_FullMethodName  = "/snaplink.admin.v1.SnapshotAdminService/Delete"
)

// SnapshotAdminServiceClient is the client API for SnapshotAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnapshotAdminService exports / restores the operator-managed state
// (clients, users, roles, assignments, menus, network policies, plus the
// bootstrap Tracker high-water mark). Every method requires the admin:*
// scope; mutations write audit events.
type SnapshotAdminServiceClient interface {
	Export(ctx context.Context, in *ExportSnapshotRequest, opts ...grpc.CallOption) (*ExportSnapshotResponse, error)
	List(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	Get(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	Restore(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error)
	Delete(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
}

type snapshotAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotAdminServiceClient(cc grpc.ClientConnInterface) SnapshotAdminServiceClient {
	return &snapshotAdminServiceClient{cc}
}

func (c *snapshotAdminServiceClient) Export(ctx context.Context, in *ExportSnapshotRequest, opts ...grpc.CallOption) (*ExportSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotAdminService_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotAdminServiceClient) List(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, SnapshotAdminService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotAdminServiceClient) Get(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotAdminService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotAdminServiceClient) Restore(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotAdminService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotAdminServiceClient) Delete(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotAdminService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotAdminServiceServer is the server API for SnapshotAdminService service.
// All implementations must embed UnimplementedSnapshotAdminServiceServer
// for forward compatibility.
//
// SnapshotAdminService exports / restores the operator-managed state
// (clients, users, roles, assignments, menus, network policies, plus the
// bootstrap Tracker high-water mark). Every method requires the admin:*
// scope; mutations write audit events.
type SnapshotAdminServiceServer interface {
	Export(context.Context, *ExportSnapshotRequest) (*ExportSnapshotResponse, error)
	List(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	Get(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	Restore(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error)
	Delete(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	mustEmbedUnimplementedSnapshotAdminServiceServer()
}

// UnimplementedSnapshotAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotAdminServiceServer struct{}

func (UnimplementedSnapshotAdminServiceServer) Export(context.Context, *ExportSnapshotRequest) (*ExportSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedSnapshotAdminServiceServer) List(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSnapshotAdminServiceServer) Get(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSnapshotAdminServiceServer) Restore(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedSnapshotAdminServiceServer) Delete(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSnapshotAdminServiceServer) mustEmbedUnimplementedSnapshotAdminServiceServer() {}
func (UnimplementedSnapshotAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeSnapshotAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotAdminServiceServer will
// result in compilation errors.
type UnsafeSnapshotAdminServiceServer interface {
	mustEmbedUnimplementedSnapshotAdminServiceServer()
}

func RegisterSnapshotAdminServiceServer(s grpc.ServiceRegistrar, srv SnapshotAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedSnapshotAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotAdminService_ServiceDesc, srv)
}

func _SnapshotAdminService_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAdminServiceServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAdminService_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAdminServiceServer).Export(ctx, req.(*ExportSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotAdminService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAdminServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAdminService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAdminServiceServer).List(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotAdminService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAdminServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAdminService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAdminServiceServer).Get(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotAdminService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAdminServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAdminService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAdminServiceServer).Restore(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotAdminService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAdminServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAdminService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAdminServiceServer).Delete(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotAdminService_ServiceDesc is the grpc.ServiceDesc for SnapshotAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snaplink.admin.v1.SnapshotAdminService",
	HandlerType: (*SnapshotAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Export",
			Handler:    _SnapshotAdminService_Export_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SnapshotAdminService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SnapshotAdminService_Get_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _SnapshotAdminService_Restore_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SnapshotAdminService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/snapshots.proto",
}
