package main

import (
	"fmt"
	"strconv"

	"strings"
)

// GeneratePython renders the full docs/sdks/python/client.py contents:
// the generated-file banner, every named component schema as a
// `TypedDict`, the small urllib-based runtime (stdlib only — no
// `requests` dependency), and one SSOClient method per curated Operation.
//
// TypedDict (not @dataclass, despite dataclasses being stdlib too) is the
// deliberate choice here: the client never actually constructs an
// instance from a JSON response (no field-by-field validation/mapping
// logic — see the package doc's scope), it just returns the parsed
// dict/list straight from json.loads. A TypedDict's static type IS a
// dict — `result["access_token"]` type-checks AND matches what's really
// at runtime; a @dataclass would type-check `result.access_token` while
// runtime `result` stays a plain dict, which is actively misleading.
func GeneratePython(title, version string, reg *Registry, ops []Operation) string {
	var b strings.Builder
	b.WriteString(pyBanner(title, version))
	b.WriteString(pyRuntimePrelude)
	b.WriteString("# ---- Types (generated from components.schemas) ----\n\n")
	for _, name := range reg.Named() {
		pyEmitNamedType(&b, name, reg.NamedType(name))
	}
	b.WriteString(pyClientHeader)
	pyEmitMethods(&b, ops)
	return b.String()
}

func pyBanner(title, version string) string {
	return fmt.Sprintf(`# Code generated by cmd/gensdk (--lang=py). DO NOT EDIT.
# Source: docs/openapi.yaml (%s %s). Regenerate: go run ./cmd/gensdk --lang=py
#
# Python client covering the operationId set declared in
# ops/build/sdk-surface.json (validated against docs/openapi.yaml and
# ops/build/capabilities.json by "python cli.py sdk-surface check").
# Every method is named from the spec's operationId (converted to
# snake_case; the original is kept in each method's docstring) so a call
# site is traceable back to its docs/openapi.yaml operation.
#
# Stdlib only: urllib.request for transport, typing.TypedDict for wire
# shapes -- no "requests", no third-party dependency of any kind.

from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Callable, Dict, List, Optional, TypedDict, Union


`, title, version)
}

// pyRuntimePrelude is the urllib-based transport every generated method
// calls through. Hand-written once rather than generated per-operation.
const pyRuntimePrelude = `class SSOError(Exception):
    """Raised on any non-2xx response; carries the parsed ErrorResponse
    fields when the body was JSON."""

    def __init__(self, status: int, error: Optional[str] = None, error_description: Optional[str] = None):
        super().__init__(error_description or error or f"sso request failed with status {status}")
        self.status = status
        self.error = error
        self.error_description = error_description


`

// pyClientHeader opens the SSOClient class + its constructor + the
// shared _request transport; pyEmitMethods fills in the per-operation
// methods after it.
const pyClientHeader = `class SSOClient:
    """Minimal, hand-scoped client for the snaplink/sso HTTP API. See the
    module docstring for exactly what operation surface this covers."""

    def __init__(self, base_url: str, get_access_token: Optional[Callable[[], Optional[str]]] = None):
        self.base_url = base_url.rstrip("/")
        self.get_access_token = get_access_token

    def _request(
        self,
        method: str,
        path: str,
        query: Optional[Dict[str, Any]] = None,
        body: Optional[Any] = None,
        auth: bool = False,
        form: bool = False,
        form_blocked_fields: Optional[List[str]] = None,
    ) -> Any:
        url = self.base_url + path
        if query:
            filtered = {k: v for k, v in query.items() if v is not None}
            if filtered:
                url += "?" + urllib.parse.urlencode(filtered)
        headers = {"Accept": "application/json"}
        data = None
        if body is not None:
            if form:
                headers["Content-Type"] = "application/x-www-form-urlencoded"
                data = _form_encode(body, form_blocked_fields).encode("utf-8")
            else:
                headers["Content-Type"] = "application/json"
                data = json.dumps(body).encode("utf-8")
        if auth and self.get_access_token:
            token = self.get_access_token()
            if token:
                headers["Authorization"] = f"Bearer {token}"
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req) as resp:
                return _parse_body(resp.status, resp.read())
        except urllib.error.HTTPError as exc:
            payload = exc.read()
            error, error_description = _parse_error(payload)
            raise SSOError(exc.code, error, error_description) from exc

`

func pyEmitMethods(b *strings.Builder, ops []Operation) {
	tag := ""
	for _, op := range ops {
		if op.Tag != tag {
			tag = op.Tag
			fmt.Fprintf(b, "    # ---- %s ----\n\n", tag)
		}
		pyEmitMethod(b, op)
	}
	b.WriteString(pyModuleHelpers)
}

// pyModuleHelpers are free functions (not methods) shared by every
// SSOClient instance — split out of the class purely for readability.
const pyModuleHelpers = `
def _form_encode(body: Dict[str, Any], blocked_fields: Optional[List[str]] = None) -> str:
    """Serialize a request body as application/x-www-form-urlencoded.

    Mirrors the Go binder in protocols/oauth/oauthwire (bind.go):
    - None values are dropped (JSON.stringify's null-drop equivalent);
    - blocked_fields keys are never emitted (no RFC defines a map form
      encoding; the generated method additionally fails loud on them);
    - bools become lowercase "true"/"false" -- urllib would emit
      "True"/"False", which the binder silently coerces to false
      (device approval denied, trust grant never minted);
    - string lists become REPEATED keys via urlencode(doseq=True) (the
      documented resource/audience/tokens contract);
    - other lists (authorization_details) and dicts (claims) become a
      single JSON-string key (RFC 9396 §3 / OIDC Core §5.5).
    """
    blocked = set(blocked_fields or [])
    encoded: Dict[str, Any] = {}
    for key, value in body.items():
        if key in blocked or value is None:
            continue
        if isinstance(value, bool):
            encoded[key] = "true" if value else "false"
        elif isinstance(value, list) and all(isinstance(item, str) for item in value):
            encoded[key] = value
        elif isinstance(value, (list, dict)):
            encoded[key] = json.dumps(value)
        else:
            encoded[key] = value
    return urllib.parse.urlencode(encoded, doseq=True)


def _parse_body(status: int, raw: bytes) -> Any:
    if status == 204 or not raw:
        return None
    return json.loads(raw)


def _parse_error(payload: bytes) -> "tuple[Optional[str], Optional[str]]":
    if not payload:
        return None, None
    try:
        parsed = json.loads(payload)
    except ValueError:
        return None, None
    return parsed.get("error"), parsed.get("error_description")
`

func pyEmitMethod(b *strings.Builder, op Operation) {
	name := pySnakeCase(op.ID)
	retType := "None"
	if op.ResultType != nil {
		retType = pyType(op.ResultType)
	}
	fmt.Fprintf(b, "    def %s(%s) -> %s:\n", name, pyMethodParams(op), retType)
	doc := op.Summary
	if doc == "" {
		doc = op.ID
	}
	fmt.Fprintf(b, "        \"\"\"%s (operationId: %s)\"\"\"\n", pySafe(doc), op.ID)
	// The guard exists because the form serializer cannot express a map;
	// JSON-only operations keep their map fields working, so only form-wire
	// operations get it (today exactly post_mfa_complete.params).
	if op.ContentType == formContentType {
		for _, f := range op.FormBlockedFields {
			// Presence-based guard (fires for params: {} too), mirroring the
			// binder's PostForm.Has semantics: a map has no form encoding, so
			// fail loud client-side instead of attempting a wire the server
			// rejects (400 mfa_invalid on /auth/mfa once the strict binder
			// lands; a silent drop today).
			fmt.Fprintf(b, "        if body.get(%q) is not None:\n", f)
			fmt.Fprintf(b, "            raise SSOError(0, \"invalid_request\", %q)\n", f+" has no application/x-www-form-urlencoded encoding; use code/assertion")
		}
	}
	fmt.Fprintf(b, "        return self._request(%q, %s", strings.ToUpper(op.Method), pyPathExpr(op.Path))
	if len(op.QueryParams) > 0 {
		b.WriteString(", query=query")
	}
	if op.HasBody {
		b.WriteString(", body=body")
	}
	if op.ContentType == formContentType {
		b.WriteString(", form=True")
		if len(op.FormBlockedFields) > 0 {
			quoted := make([]string, len(op.FormBlockedFields))
			for i, f := range op.FormBlockedFields {
				quoted[i] = strconv.Quote(f)
			}
			b.WriteString(", form_blocked_fields=[" + strings.Join(quoted, ", ") + "]")
		}
	}
	if op.RequiresAuth {
		b.WriteString(", auth=True")
	}
	b.WriteString(")\n\n")
}

// pyMethodParams orders parameters the way Python requires: every
// default-less parameter (path params; a REQUIRED body) before every
// parameter with a default (an optional body; the query dict).
func pyMethodParams(op Operation) string {
	var required, optional []string
	for _, p := range op.PathParams {
		required = append(required, p.Name+": str")
	}
	bodyType := "Dict[str, Any]"
	if op.BodyType != nil {
		bodyType = pyType(op.BodyType)
	}
	if op.HasBody {
		if op.BodyRequired {
			required = append(required, "body: "+bodyType)
		} else {
			optional = append(optional, "body: Optional["+bodyType+"] = None")
		}
	}
	if len(op.QueryParams) > 0 {
		optional = append(optional, "query: Optional[Dict[str, Any]] = None")
	}
	parts := append([]string{"self"}, required...)
	parts = append(parts, optional...)
	return strings.Join(parts, ", ")
}

// pyPathExpr renders path as a Python f-string, substituting each
// {name} with urllib.parse.quote(name) — OpenAPI parameter names are
// already snake_case, so no identifier translation is needed (unlike
// tsPathExpr's camelCase conversion).
//
// Scans the ORIGINAL path with a forward-only cursor rather than
// mutate-and-rescan — see tsPathExpr's doc for why re-scanning the
// growing output (which contains the f-string's OWN "{"/"}" syntax)
// would never terminate.
func pyPathExpr(path string) string {
	if !strings.Contains(path, "{") {
		return fmt.Sprintf("%q", path)
	}
	var b strings.Builder
	b.WriteString(`f"`)
	i := 0
	for i < len(path) {
		start := strings.IndexByte(path[i:], '{')
		if start < 0 {
			b.WriteString(path[i:])
			break
		}
		start += i
		end := strings.IndexByte(path[start:], '}')
		if end < 0 {
			b.WriteString(path[i:])
			break
		}
		end += start
		b.WriteString(path[i:start])
		name := path[start+1 : end]
		b.WriteString("{urllib.parse.quote(" + name + ")}")
		i = end + 1
	}
	b.WriteByte('"')
	return b.String()
}

// pySnakeCase converts a camelCase operationId (e.g. "postToken") to
// snake_case ("post_token") for a PEP 8-idiomatic method name. Treats a
// run of uppercase letters as one acronym (e.g. "getJWKS" -> "get_jwks",
// "getClientByID" -> "get_client_by_id") rather than splitting every
// letter — a simple heuristic, not an acronym dictionary; see the
// package doc.
func pySnakeCase(s string) string {
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if isUpper(r) {
			prevLower := i > 0 && isLower(runes[i-1])
			nextLower := i+1 < len(runes) && isLower(runes[i+1])
			boundary := prevLower || (nextLower && i > 0 && isUpper(runes[i-1]))
			if i > 0 && boundary {
				b.WriteByte('_')
			}
			b.WriteRune(toLower(r))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func isUpper(r rune) bool { return r >= 'A' && r <= 'Z' }
func isLower(r rune) bool { return r >= 'a' && r <= 'z' }
func toLower(r rune) rune {
	if isUpper(r) {
		return r + ('a' - 'A')
	}
	return r
}

// pySafe makes a description/summary line safe to place inside a
// `"""..."""` docstring.
func pySafe(s string) string {
	return strings.ReplaceAll(s, `"""`, "'''")
}

// pyType renders a TypeSpec as a Python type hint. nil (no response
// body) renders as "None".
func pyType(t *TypeSpec) string {
	if t == nil {
		return "None"
	}
	switch t.Kind {
	case KindString:
		return "str" // enum values are simplified to str; see README
	case KindInteger:
		return "int"
	case KindNumber:
		return "float"
	case KindBoolean:
		return "bool"
	case KindArray:
		return "List[" + pyType(t.Elem) + "]"
	case KindMap:
		return "Dict[str, " + pyType(t.Elem) + "]"
	case KindRef:
		return t.Name
	case KindUnion:
		return pyUnion(t.Variants)
	case KindObject:
		return "Dict[str, Any]" // named-field object with no $ref: no synthesized TypedDict, see README
	default:
		return "Any"
	}
}

func pyUnion(variants []*TypeSpec) string {
	seen := map[string]bool{}
	var parts []string
	for _, v := range variants {
		s := pyType(v)
		if !seen[s] {
			seen[s] = true
			parts = append(parts, s)
		}
	}
	switch len(parts) {
	case 0:
		return "Any"
	case 1:
		return parts[0]
	default:
		return "Union[" + strings.Join(parts, ", ") + "]"
	}
}

// pyEmitNamedType renders one components.schemas entry as a `TypedDict`
// subclass (object with named fields), a `List[...]` type alias (a
// top-level array schema, e.g. MenuTree), or a plain type-alias
// assignment for anything else (map/union/primitive).
//
// total=False on every generated TypedDict is a deliberate simplification:
// it makes every key optional to the type checker rather than encoding
// this generator's `required` list precisely (which would need
// Required[]/NotRequired[] — Python 3.11+ — or a two-class split; see
// README). At runtime TypedDict enforces nothing either way.
func pyEmitNamedType(b *strings.Builder, name string, t *TypeSpec) {
	switch {
	case t.Kind == KindArray:
		fmt.Fprintf(b, "%s = List[%s]\n\n\n", name, pyType(t.Elem))
	case t.Kind == KindObject && len(t.Fields) > 0:
		fmt.Fprintf(b, "class %s(TypedDict, total=False):\n", name)
		if t.Doc != "" {
			fmt.Fprintf(b, "    \"\"\"%s\"\"\"\n", pySafe(t.Doc))
		}
		for _, f := range t.Fields {
			fmt.Fprintf(b, "    %s: %s", pyFieldName(f.Name), pyType(f.Type))
			if f.Doc != "" {
				fmt.Fprintf(b, "  # %s", pySafe(f.Doc))
			}
			b.WriteString("\n")
		}
		b.WriteString("\n\n")
	default:
		fmt.Fprintf(b, "%s = %s\n\n\n", name, pyType(t))
	}
}
