package main

import (
	"fmt"
	"strconv"
	"strings"
)

// GeneratePython renders the full docs/sdks/python/client.py contents:
// the generated-file banner, every named component schema as a
// `TypedDict`, the small urllib-based runtime (stdlib only — no
// `requests` dependency), and one SSOClient method per curated Operation.
//
// TypedDict (not @dataclass, despite dataclasses being stdlib too) is the
// deliberate choice here: the client never actually constructs an
// instance from a JSON response (no field-by-field validation/mapping
// logic — see the package doc's scope), it just returns the parsed
// dict/list straight from json.loads. A TypedDict's static type IS a
// dict — `result["access_token"]` type-checks AND matches what's really
// at runtime; a @dataclass would type-check `result.access_token` while
// runtime `result` stays a plain dict, which is actively misleading.
func GeneratePython(title, version string, reg *Registry, ops []Operation) string {
	var b strings.Builder
	b.WriteString(pyBanner(title, version))
	b.WriteString(pyRuntimePrelude)
	b.WriteString("# ---- Types (generated from components.schemas) ----\n\n")
	for _, name := range reg.Named() {
		pyEmitNamedType(&b, name, reg.NamedType(name))
	}
	b.WriteString(pyClientHeader)
	pyEmitMethods(&b, ops)
	pyEmitExports(&b, reg.Named())
	return b.String()
}

func pyBanner(title, version string) string {
	return fmt.Sprintf(`# Code generated by cmd/gensdk (--lang=py). DO NOT EDIT.
# Source: docs/openapi.yaml (%s %s). Regenerate: go run ./cmd/gensdk --lang=py
#
# Python client covering the operationId set declared in
# ops/build/sdk-surface.json (validated against docs/openapi.yaml and
# ops/build/capabilities.json by "python cli.py sdk-surface check").
# Every method is named from the spec's operationId (converted to
# snake_case; the original is kept in each method's docstring) so a call
# site is traceable back to its docs/openapi.yaml operation.
#
# Stdlib only: urllib.request for transport, typing.TypedDict for wire
# shapes -- no "requests", no third-party dependency of any kind.

from __future__ import annotations

import base64
import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Callable, Dict, List, Optional, TypedDict, Union


`, title, version)
}

// pyRuntimePrelude is the urllib-based transport every generated method
// calls through. Hand-written once rather than generated per-operation.
const pyRuntimePrelude = `class SSOError(Exception):
    """Raised on any non-2xx response; carries the parsed ErrorResponse
    fields when the body was JSON."""

    def __init__(self, status: int, error: Optional[str] = None, error_description: Optional[str] = None):
        super().__init__(error_description or error or f"sso request failed with status {status}")
        self.status = status
        self.error = error
        self.error_description = error_description


`

// pyClientHeader opens the SSOClient class + its constructor + the
// shared _request transport; pyEmitMethods fills in the per-operation
// methods after it.
const pyClientHeader = `class SSOClient:
    """Minimal, hand-scoped client for the snaplink/sso HTTP API. See the
    module docstring for exactly what operation surface this covers."""

    def __init__(
        self,
        base_url: str,
        get_access_token: Optional[Callable[[], Optional[str]]] = None,
        *,
        client_id: Optional[str] = None,
        client_secret: Optional[str] = None,
        request_timeout: Optional[float] = None,
    ):
        self.base_url = base_url.rstrip("/")
        self.client_id = client_id
        self.client_secret = client_secret
        self.request_timeout = request_timeout
        self._token: Optional[str] = None
        self.get_access_token = get_access_token or (lambda: self._token)

    @property
    def is_logged_in(self) -> bool:
        return bool(self._token)

    @property
    def access_token(self) -> Optional[str]:
        return self._token

    def login(
        self,
        username: str,
        password: str,
        *,
        client_id: Optional[str] = None,
        scope: Optional[List[str]] = None,
        extra_credential: Optional[Dict[str, str]] = None,
    ) -> Union[LoginResponse, MFARequiredResponse]:
        resolved_client_id = client_id or self.client_id
        if not resolved_client_id:
            raise SSOError(0, "invalid_request", "client_id is required")
        credential: Dict[str, str] = {"username": username, "password": password}
        if extra_credential:
            credential.update(extra_credential)
        response = self.post_login({
            "provider": "password",
            "client_id": resolved_client_id,
            "scope": scope or ["openid", "profile", "email"],
            "credential": credential,
        })
        self._capture_token(response)
        return response

    def complete_mfa(self, body: MFACompleteRequest) -> Union[LoginResponse, AuthorizationCodeResponse]:
        response = self.post_mfa_complete(body)
        self._capture_token(response)
        return response

    def logout(self) -> None:
        try:
            if self._token:
                self.post_logout({})
        finally:
            self._token = None

    def _capture_token(self, response: Any) -> None:
        if isinstance(response, dict) and response.get("access_token"):
            self._token = response["access_token"]

    def _request(
        self,
        method: str,
        path: str,
        query: Optional[Dict[str, Any]] = None,
        body: Optional[Any] = None,
        auth: bool = False,
        form: bool = False,
        form_blocked_fields: Optional[List[str]] = None,
        client_auth: bool = False,
    ) -> Any:
        url = self.base_url + path
        if query:
            filtered = {k: v for k, v in query.items() if v is not None}
            if filtered:
                url += "?" + urllib.parse.urlencode(filtered)
        headers = {"Accept": "application/json"}
        authenticated_body = self._with_client_auth(body, headers) if client_auth else body
        data = None
        if authenticated_body is not None:
            if form:
                headers["Content-Type"] = "application/x-www-form-urlencoded"
                data = _form_encode(authenticated_body, form_blocked_fields).encode("utf-8")
            else:
                headers["Content-Type"] = "application/json"
                data = json.dumps(authenticated_body).encode("utf-8")
        if auth and self.get_access_token:
            token = self.get_access_token()
            if token:
                headers["Authorization"] = f"Bearer {token}"
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            opener = urllib.request.urlopen
            if self.request_timeout is None:
                response = opener(req)
            else:
                response = opener(req, timeout=self.request_timeout)
            with response as resp:
                return _parse_body(resp.status, resp.read())
        except urllib.error.HTTPError as exc:
            payload = exc.read()
            error, error_description = _parse_error(payload)
            raise SSOError(exc.code, error, error_description) from exc

    def _with_client_auth(self, body: Optional[Any], headers: Dict[str, str]) -> Optional[Any]:
        if not self.client_secret:
            return body
        body_map = body if isinstance(body, dict) else {}
        client_id = self.client_id or body_map.get("client_id")
        if not client_id:
            raise SSOError(0, "invalid_request", "client_id is required with client_secret")
        credentials = f"{client_id}:{self.client_secret}".encode("utf-8")
        headers["Authorization"] = "Basic " + base64.b64encode(credentials).decode("ascii")
        if not isinstance(body, dict):
            return body
        without_credentials = dict(body)
        without_credentials.pop("client_id", None)
        without_credentials.pop("client_secret", None)
        return without_credentials

`

func pyEmitMethods(b *strings.Builder, ops []Operation) {
	tag := ""
	for _, op := range ops {
		if op.Tag != tag {
			tag = op.Tag
			fmt.Fprintf(b, "    # ---- %s ----\n\n", tag)
		}
		pyEmitMethod(b, op)
	}
	b.WriteString(pyModuleHelpers)
}

// pyModuleHelpers are free functions (not methods) shared by every
// SSOClient instance — split out of the class purely for readability.
const pyModuleHelpers = `
def _form_encode(body: Dict[str, Any], blocked_fields: Optional[List[str]] = None) -> str:
    """Serialize a request body as application/x-www-form-urlencoded.

    Mirrors the Go binder in protocols/oauth/oauthwire (bind.go):
    - None values are dropped (JSON.stringify's null-drop equivalent);
    - blocked_fields keys are never emitted (no RFC defines a map form
      encoding; the generated method additionally fails loud on them);
    - bools become lowercase "true"/"false" -- urllib would emit
      "True"/"False", which the binder silently coerces to false
      (device approval denied, trust grant never minted);
    - string lists become REPEATED keys via urlencode(doseq=True) (the
      documented resource/audience/tokens contract);
    - other lists (authorization_details) and dicts (claims) become a
      single JSON-string key (RFC 9396 §3 / OIDC Core §5.5).
    """
    blocked = set(blocked_fields or [])
    encoded: Dict[str, Any] = {}
    for key, value in body.items():
        if key in blocked or value is None:
            continue
        if isinstance(value, bool):
            encoded[key] = "true" if value else "false"
        elif isinstance(value, list) and all(isinstance(item, str) for item in value):
            encoded[key] = value
        elif isinstance(value, (list, dict)):
            encoded[key] = json.dumps(value)
        else:
            encoded[key] = value
    return urllib.parse.urlencode(encoded, doseq=True)


def _parse_body(status: int, raw: bytes) -> Any:
    if status == 204 or not raw:
        return None
    return json.loads(raw)


def _parse_error(payload: bytes) -> "tuple[Optional[str], Optional[str]]":
    if not payload:
        return None, None
    try:
        parsed = json.loads(payload)
    except ValueError:
        return None, None
    return parsed.get("error"), parsed.get("error_description")
`

func pyEmitMethod(b *strings.Builder, op Operation) {
	name := pySnakeCase(op.ID)
	retType := "None"
	if op.ResultType != nil {
		retType = pyType(op.ResultType)
	}
	fmt.Fprintf(b, "    def %s(%s) -> %s:\n", name, pyMethodParams(op), retType)
	doc := op.Summary
	if doc == "" {
		doc = op.ID
	}
	fmt.Fprintf(b, "        \"\"\"%s (operationId: %s)\"\"\"\n", pySafe(doc), op.ID)
	pyEmitFormBlockedGuard(b, op)
	fmt.Fprintf(b, "        return self._request(%q, %s", strings.ToUpper(op.Method), pyPathExpr(op.Path))
	if len(op.QueryParams) > 0 {
		b.WriteString(", query=query")
	}
	if op.HasBody {
		b.WriteString(", body=body")
	}
	if op.ContentType == formContentType {
		b.WriteString(", form=True")
		if len(op.FormBlockedFields) > 0 {
			quoted := make([]string, len(op.FormBlockedFields))
			for i, f := range op.FormBlockedFields {
				quoted[i] = strconv.Quote(f)
			}
			b.WriteString(", form_blocked_fields=[" + strings.Join(quoted, ", ") + "]")
		}
	}
	if op.RequiresAuth {
		b.WriteString(", auth=True")
	}
	if pyUsesClientAuth(op.ID) {
		b.WriteString(", client_auth=True")
	}
	b.WriteString(")\n\n")
}

// pyEmitFormBlockedGuard emits a presence-based client-side guard for form-wire
// operations whose fields a form serializer cannot express (a map has no form
// encoding). Mirrors the binder's PostForm.Has semantics: fail loud client-side
// instead of attempting a wire the server rejects.
func pyEmitFormBlockedGuard(b *strings.Builder, op Operation) {
	// JSON-only operations keep their map fields working, so only form-wire
	// operations get the guard (today exactly post_mfa_complete.params).
	if op.ContentType != formContentType {
		return
	}
	for _, f := range op.FormBlockedFields {
		fmt.Fprintf(b, "        if body.get(%q) is not None:\n", f)
		fmt.Fprintf(b, "            raise SSOError(0, \"invalid_request\", %q)\n", f+" has no application/x-www-form-urlencoded encoding; use code/assertion")
	}
}

func pyUsesClientAuth(operationID string) bool {
	switch operationID {
	case "postToken", "postIntrospect", "postRevoke", "postPAR":
		return true
	default:
		return false
	}
}

func pyEmitExports(b *strings.Builder, names []string) {
	b.WriteString("\n__all__ = [\n    \"SSOError\",\n    \"SSOClient\",\n")
	for _, name := range names {
		fmt.Fprintf(b, "    %q,\n", name)
	}
	b.WriteString("]\n")
}

// pyMethodParams orders parameters the way Python requires: every
// default-less parameter (path params; a REQUIRED body) before every
// parameter with a default (an optional body; the query dict).
