package main

import (
	"fmt"
	"strconv"
	"strings"
)

// GenerateTS renders the full docs/sdks/typescript/client.ts contents:
// the generated-file banner, every named component schema as an
// `interface`/`type`, the small fetch-based runtime, and one SSOClient
// method per curated Operation.
func GenerateTS(title, version string, reg *Registry, ops []Operation) string {
	var b strings.Builder
	b.WriteString(tsBanner(title, version))
	b.WriteString(tsRuntime)
	b.WriteString("// ---- Types (generated from components.schemas) ----\n\n")
	for _, name := range reg.Named() {
		tsEmitNamedType(&b, name, reg.NamedType(name))
	}
	b.WriteString(tsClientHeader)
	tsEmitMethods(&b, ops)
	b.WriteString("}\n")
	return b.String()
}

func tsBanner(title, version string) string {
	return fmt.Sprintf(`// Code generated by cmd/gensdk (--lang=ts). DO NOT EDIT.
// Source: docs/openapi.yaml (%s %s). Regenerate: go run ./cmd/gensdk --lang=ts
//
// Minimal, hand-scoped TypeScript client — see docs/sdks/typescript/README.md
// for exactly what operationId set this covers (core OAuth2/OIDC + token
// lifecycle + self-service + a small representative admin sample) and what
// is deliberately deferred (the full ~150-route admin/SCIM/CAEP/federation
// surface). Every method name is the spec's operationId verbatim — no
// derived/shortened aliasing — so a call site is grep-able straight back to
// its docs/openapi.yaml operation.

`, title, version)
}

// tsRuntime is the fetch-based transport every generated method calls
// through. Hand-written once rather than generated per-operation.
const tsRuntime = `export interface SSOClientOptions {
  /** Base URL of the snaplink/sso deployment, e.g. "https://sso.example.com". */
  baseUrl: string;
  /** This application's registered client_id. Set it here so login(user, pass)
   *  needs only credentials. */
  clientId?: string;
  /** Injectable fetch (tests, non-global runtimes). Defaults to globalThis.fetch. */
  fetch?: typeof fetch;
  /** Returns the bearer token for auth-required calls (getMe, revokeMySessions, ...).
   *  Omit it: after login() the SDK holds the access token and auto-attaches it. */
  getAccessToken?: () => string | undefined | Promise<string | undefined>;
}

/** Thrown on any non-2xx response; carries the parsed ErrorResponse when the body was JSON. */
export class SSOError extends Error {
  constructor(
    public status: number,
    public error?: string,
    public errorDescription?: string,
  ) {
    super(errorDescription || error || ` + "`sso request failed with status ${status}`" + `);
    this.name = "SSOError";
  }
}

interface requestOptions {
  query?: Record<string, string | number | boolean | undefined>;
  body?: unknown;
  auth?: boolean;
}

`

// tsClientHeader opens the SSOClient class; tsEmitMethods fills the body,
// GenerateTS closes it with the final "}\n".
const tsClientHeader = `export class SSOClient {
  private readonly baseUrl: string;
  private readonly clientId?: string;
  private readonly fetchImpl: typeof fetch;
  private readonly getAccessToken?: () => string | undefined | Promise<string | undefined>;
  /** Access token captured by login(); auto-attached to auth-required calls. */
  private token?: string;

  constructor(opts: SSOClientOptions) {
    this.baseUrl = opts.baseUrl.replace(/\/+$/, "");
    this.clientId = opts.clientId;
    this.fetchImpl = opts.fetch ?? fetch;
    // Default token source is the token login() captured, so getUserInfo() etc.
    // work right after login without wiring anything.
    this.getAccessToken = opts.getAccessToken ?? (() => this.token);
  }

  /** True once login() succeeded and a token is held. */
  get isLoggedIn(): boolean {
    return !!this.token;
  }

  /** The access token captured by login() (undefined before login/after logout). */
  get accessToken(): string | undefined {
    return this.token;
  }

  /**
   * Password login: fills in the configured client_id and returns the auth
   * info (access_token / id_token / refresh_token / ...) directly — no redirect.
   * The token is captured internally so subsequent getUserInfo()/getMe() calls
   * auto-attach it. This is the simplest integration:
   *
   *   const sso = new SSOClient({ baseUrl, clientId: "my-app" });
   *   const auth = await sso.login(username, password);
   *   const me = await sso.getUserInfo();
   */
  async login(
    username: string,
    password: string,
    opts?: { clientId?: string; scope?: string[]; extraCredential?: Record<string, string> },
  ): Promise<LoginResponse> {
    const clientId = opts?.clientId ?? this.clientId;
    if (!clientId) {
      throw new SSOError(0, "invalid_request", "clientId is required (set it in the constructor or pass it to login)");
    }
    const resp = (await this.postLogin({
      provider: "password",
      client_id: clientId,
      scope: opts?.scope ?? ["openid", "profile", "email"],
      credential: { username, password, ...(opts?.extraCredential ?? {}) },
    })) as LoginResponse;
    if (resp && resp.access_token) this.token = resp.access_token;
    return resp;
  }

  /** Clear the held token and best-effort revoke the server session. */
  async logout(): Promise<void> {
    try {
      if (this.token) await this.postLogout({});
    } finally {
      this.token = undefined;
    }
  }

  private async request<T>(method: string, path: string, opts: requestOptions = {}): Promise<T> {
    let url = this.baseUrl + path;
    if (opts.query) {
      const qs = new URLSearchParams();
      for (const [k, v] of Object.entries(opts.query)) {
        if (v !== undefined) qs.set(k, String(v));
      }
      const s = qs.toString();
      if (s) url += "?" + s;
    }
    const headers: Record<string, string> = { Accept: "application/json" };
    let body: string | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      body = JSON.stringify(opts.body);
    }
    if (opts.auth && this.getAccessToken) {
      const token = await this.getAccessToken();
      if (token) headers["Authorization"] = ` + "`Bearer ${token}`" + `;
    }
    const res = await this.fetchImpl(url, { method, headers, body });
    if (!res.ok) {
      let error: string | undefined;
      let errorDescription: string | undefined;
      try {
        const parsed = await res.json();
        error = parsed?.error;
        errorDescription = parsed?.error_description;
      } catch {
        // non-JSON error body; SSOError falls back to a generic message.
      }
      throw new SSOError(res.status, error, errorDescription);
    }
    if (res.status === 204) return undefined as T;
    const text = await res.text();
    return (text ? JSON.parse(text) : undefined) as T;
  }

`

func tsEmitMethods(b *strings.Builder, ops []Operation) {
	tag := ""
	for _, op := range ops {
		if op.Tag != tag {
			tag = op.Tag
			fmt.Fprintf(b, "  // ---- %s ----\n\n", tag)
		}
		tsEmitMethod(b, op)
	}
}

func tsEmitMethod(b *strings.Builder, op Operation) {
	if op.Summary != "" {
		fmt.Fprintf(b, "  /** %s */\n", jsSafe(op.Summary))
	}
	retType := "void"
	if op.ResultType != nil {
		retType = tsType(op.ResultType)
	}
	fmt.Fprintf(b, "  async %s(%s): Promise<%s> {\n", op.ID, tsMethodSignature(op), retType)
	fmt.Fprintf(b, "    return this.request<%s>(%q, %s, {", retType, strings.ToUpper(op.Method), tsPathExpr(op.Path))
	tsEmitRequestOpts(b, op)
	b.WriteString(");\n  }\n\n")
}

// tsEmitRequestOpts writes the inline requestOptions object literal
// passed to request<T> — only the fields this operation actually needs.
func tsEmitRequestOpts(b *strings.Builder, op Operation) {
	var parts []string
	if len(op.QueryParams) > 0 {
		parts = append(parts, "query")
	}
	if op.HasBody {
		parts = append(parts, "body")
	}
	if op.RequiresAuth {
		parts = append(parts, "auth: true")
	}
	if len(parts) == 0 {
		b.WriteString("}")
		return
	}
	b.WriteString(" " + strings.Join(parts, ", ") + " }")
}

func tsMethodSignature(op Operation) string {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, camelCase(p.Name)+": string")
	}
	if len(op.QueryParams) > 0 {
		params = append(params, "query?: "+tsInlineParams(op.QueryParams))
	}
	if op.HasBody {
		opt := ""
		if !op.BodyRequired {
			opt = "?"
		}
		bodyType := "unknown"
		if op.BodyType != nil {
			bodyType = tsType(op.BodyType)
		}
		params = append(params, "body"+opt+": "+bodyType)
	}
	return strings.Join(params, ", ")
}

func tsInlineParams(params []Param) string {
	fields := make([]string, len(params))
	for i, p := range params {
		fields[i] = camelCase(p.Name) + "?: " + tsType(p.Type)
	}
	return "{ " + strings.Join(fields, "; ") + " }"
}

// tsPathExpr renders path (e.g. "/register/{client_id}") as a JS template
// literal, substituting each {name} with the encodeURIComponent'd path
// parameter — path params always come first in the method signature (see
// tsMethodSignature), so the identifier this refers to is always in scope.
//
// Scans the ORIGINAL path with a forward-only cursor rather than
// mutate-and-rescan: the substitution text itself contains "${" and "}"
// (JS template-literal syntax), so re-scanning the growing output string
// for the next "{" would keep finding the substitution's OWN braces
// forever.
func tsPathExpr(path string) string {
	var b strings.Builder
	b.WriteByte('`')
	i := 0
	for i < len(path) {
		start := strings.IndexByte(path[i:], '{')
		if start < 0 {
			b.WriteString(path[i:])
			break
		}
		start += i
		end := strings.IndexByte(path[start:], '}')
		if end < 0 {
			b.WriteString(path[i:])
			break
		}
		end += start
		b.WriteString(path[i:start])
		name := path[start+1 : end]
		b.WriteString("${encodeURIComponent(" + camelCase(name) + ")}")
		i = end + 1
	}
	b.WriteByte('`')
	return b.String()
}

// camelCase converts a snake_case OpenAPI parameter/field name (e.g.
// "client_id") to lowerCamelCase ("clientId") for use as a JS identifier.
func camelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

// jsSafe makes a description/summary line safe to place inside a
// `/** ... */` JSDoc comment (the only place free-text spec prose lands in
// the generated file).
func jsSafe(s string) string {
	return strings.ReplaceAll(s, "*/", "* /")
}

// tsType renders a TypeSpec as a TypeScript type expression. nil (no
// response body) renders as "void" so callers building a return type don't
// need a separate nil check.
func tsType(t *TypeSpec) string {
	if t == nil {
		return "void"
	}
	switch t.Kind {
	case KindString:
		if len(t.Enum) > 0 {
			return tsEnumUnion(t.Enum)
		}
		return "string"
	case KindInteger, KindNumber:
		return "number"
	case KindBoolean:
		return "boolean"
	case KindArray:
		return tsType(t.Elem) + "[]"
	case KindMap:
		return "Record<string, " + tsType(t.Elem) + ">"
	case KindRef:
		return t.Name
	case KindUnion:
		return tsUnion(t.Variants)
	case KindObject:
		if len(t.Fields) == 0 {
			return "Record<string, unknown>"
		}
		return tsInlineObject(t)
	default:
		return "unknown"
	}
}

func tsEnumUnion(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.Quote(v)
	}
	return strings.Join(parts, " | ")
}

func tsUnion(variants []*TypeSpec) string {
	seen := map[string]bool{}
	var parts []string
	for _, v := range variants {
		s := tsType(v)
		if !seen[s] {
			seen[s] = true
			parts = append(parts, s)
		}
	}
	if len(parts) == 0 {
		return "unknown"
	}
	return strings.Join(parts, " | ")
}

func tsInlineObject(t *TypeSpec) string {
	var b strings.Builder
	b.WriteString("{ ")
	for i, f := range t.Fields {
		if i > 0 {
			b.WriteString("; ")
		}
		b.WriteString(f.Name)
		if !f.Required {
			b.WriteString("?")
		}
		b.WriteString(": ")
		b.WriteString(tsType(f.Type))
	}
	b.WriteString(" }")
	return b.String()
}

// tsEmitNamedType renders one components.schemas entry as an `export
// interface` (object with named fields), an `export type X = Y[]` (a
// top-level array schema, e.g. MenuTree), or an `export type X = ...`
// type alias for anything else (map/union/primitive/enum).
func tsEmitNamedType(b *strings.Builder, name string, t *TypeSpec) {
	if t.Doc != "" {
		fmt.Fprintf(b, "/** %s */\n", jsSafe(t.Doc))
	}
	switch {
	case t.Kind == KindArray:
		fmt.Fprintf(b, "export type %s = %s[];\n\n", name, tsType(t.Elem))
	case t.Kind == KindObject && len(t.Fields) > 0:
		fmt.Fprintf(b, "export interface %s {\n", name)
		for _, f := range t.Fields {
			if f.Doc != "" {
				fmt.Fprintf(b, "  /** %s */\n", jsSafe(f.Doc))
			}
			opt := ""
			if !f.Required {
				opt = "?"
			}
			fmt.Fprintf(b, "  %s%s: %s;\n", f.Name, opt, tsType(f.Type))
		}
		b.WriteString("}\n\n")
	default:
		fmt.Fprintf(b, "export type %s = %s;\n\n", name, tsType(t))
	}
}
