package main

import (
	"fmt"
	"strconv"
	"strings"
)

// GenerateTS renders the full docs/sdks/typescript/client.ts contents:
// the generated-file banner, every named component schema as an
// `interface`/`type`, the small fetch-based runtime, and one SSOClient
// method per curated Operation.
func GenerateTS(title, version string, reg *Registry, ops []Operation) string {
	var b strings.Builder
	b.WriteString(tsBanner(title, version))
	b.WriteString(tsRuntime)
	b.WriteString("// ---- Types (generated from components.schemas) ----\n\n")
	for _, name := range reg.Named() {
		tsEmitNamedType(&b, name, reg.NamedType(name))
	}
	b.WriteString(tsClientHeader)
	tsEmitMethods(&b, ops)
	b.WriteString("}\n")
	return b.String()
}

func tsBanner(title, version string) string {
	return fmt.Sprintf(`// Code generated by cmd/gensdk (--lang=ts). DO NOT EDIT.
// Source: docs/openapi.yaml (%s %s). Regenerate: go run ./cmd/gensdk --lang=ts
//
// TypeScript client covering the operationId set declared in
// ops/build/sdk-surface.json (validated against docs/openapi.yaml and
// ops/build/capabilities.json by "python cli.py sdk-surface check").
// Every method name is the spec's operationId verbatim — no
// derived/shortened aliasing — so a call site is grep-able straight back to
// its docs/openapi.yaml operation.

`, title, version)
}

func tsEmitMethods(b *strings.Builder, ops []Operation) {
	tag := ""
	for _, op := range ops {
		if op.Tag != tag {
			tag = op.Tag
			fmt.Fprintf(b, "  // ---- %s ----\n\n", tag)
		}
		tsEmitMethod(b, op)
	}
}

func tsEmitMethod(b *strings.Builder, op Operation) {
	if op.Summary != "" {
		fmt.Fprintf(b, "  /** %s */\n", jsSafe(op.Summary))
	}
	retType := "void"
	if op.ResultType != nil {
		retType = tsType(op.ResultType)
	}
	fmt.Fprintf(b, "  async %s(%s): Promise<%s> {\n", op.ID, tsMethodSignature(op), retType)
	// The guard exists because the form serializer cannot express a map;
	// JSON-only operations keep their map fields working, so only form-wire
	// operations get it (today exactly postMFAComplete.params).
	if op.ContentType == formContentType {
		for _, f := range op.FormBlockedFields {
			// Presence-based guard (fires for params: {} too), mirroring the
			// binder's PostForm.Has semantics: a map has no form encoding, so
			// fail loud client-side instead of attempting a wire the server
			// rejects (400 mfa_invalid on /auth/mfa once the strict binder
			// lands; a silent drop today).
			fmt.Fprintf(b, "    if (body.%s !== undefined && body.%s !== null) {\n", f, f)
			fmt.Fprintf(b, "      throw new SSOError(0, \"invalid_request\", %s);\n", strconv.Quote(f+" has no application/x-www-form-urlencoded encoding; use code/assertion"))
			fmt.Fprintf(b, "    }\n")
		}
	}
	fmt.Fprintf(b, "    return this.request<%s>(%q, %s, {", retType, strings.ToUpper(op.Method), tsPathExpr(op.Path))
	tsEmitRequestOpts(b, op)
	b.WriteString(");\n  }\n\n")
}

// tsEmitRequestOpts writes the inline requestOptions object literal
// passed to request<T> — only the fields this operation actually needs.
func tsEmitRequestOpts(b *strings.Builder, op Operation) {
	var parts []string
	if len(op.QueryParams) > 0 {
		parts = append(parts, "query: "+tsWireQuery(op.QueryParams))
	}
	if op.HasBody {
		parts = append(parts, "body")
	}
	if op.RequiresAuth {
		parts = append(parts, "auth: true")
	}
	if tsUsesClientAuth(op.ID) {
		parts = append(parts, "clientAuth: true")
	}
	if op.ContentType == formContentType {
		parts = append(parts, "form: true")
		if len(op.FormBlockedFields) > 0 {
			quoted := make([]string, len(op.FormBlockedFields))
			for i, f := range op.FormBlockedFields {
				quoted[i] = strconv.Quote(f)
			}
			parts = append(parts, "formBlockedFields: ["+strings.Join(quoted, ", ")+"]")
		}
	}
	if len(parts) == 0 {
		b.WriteString("}")
		return
	}
	b.WriteString(" " + strings.Join(parts, ", ") + " }")
}

// tsWireQuery keeps ergonomic camelCase call-site names while preserving
// the OpenAPI parameter names sent over HTTP.
func tsWireQuery(params []Param) string {
	fields := make([]string, len(params))
	for i, p := range params {
		fields[i] = strconv.Quote(p.Name) + ": query?." + camelCase(p.Name)
	}
	return "{ " + strings.Join(fields, ", ") + " }"
}

func tsUsesClientAuth(operationID string) bool {
	switch operationID {
	case "postToken", "postIntrospect", "postRevoke", "postPAR":
		return true
	default:
		return false
	}
}

func tsMethodSignature(op Operation) string {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, camelCase(p.Name)+": string")
	}
	if op.HasBody {
		opt := ""
		if !op.BodyRequired {
			opt = "?"
		}
		bodyType := "unknown"
		if op.BodyType != nil {
			bodyType = tsType(op.BodyType)
		}
		params = append(params, "body"+opt+": "+bodyType)
	}
	if len(op.QueryParams) > 0 {
		params = append(params, "query?: "+tsInlineParams(op.QueryParams))
	}
	return strings.Join(params, ", ")
}

func tsInlineParams(params []Param) string {
	fields := make([]string, len(params))
	for i, p := range params {
		fields[i] = camelCase(p.Name) + "?: " + tsType(p.Type)
	}
	return "{ " + strings.Join(fields, "; ") + " }"
}

// tsPathExpr renders path (e.g. "/register/{client_id}") as a JS template
// literal, substituting each {name} with the encodeURIComponent'd path
// parameter — path params always come first in the method signature (see
// tsMethodSignature), so the identifier this refers to is always in scope.
//
// Scans the ORIGINAL path with a forward-only cursor rather than
// mutate-and-rescan: the substitution text itself contains "${" and "}"
// (JS template-literal syntax), so re-scanning the growing output string
// for the next "{" would keep finding the substitution's OWN braces
// forever.
func tsPathExpr(path string) string {
	var b strings.Builder
	b.WriteByte('`')
	i := 0
	for i < len(path) {
		start := strings.IndexByte(path[i:], '{')
		if start < 0 {
			b.WriteString(path[i:])
			break
		}
		start += i
		end := strings.IndexByte(path[start:], '}')
		if end < 0 {
			b.WriteString(path[i:])
			break
		}
		end += start
		b.WriteString(path[i:start])
		name := path[start+1 : end]
		b.WriteString("${encodeURIComponent(" + camelCase(name) + ")}")
		i = end + 1
	}
	b.WriteByte('`')
	return b.String()
}

// camelCase converts a snake_case OpenAPI parameter/field name (e.g.
// "client_id") to lowerCamelCase ("clientId") for use as a JS identifier.
func camelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

// jsSafe makes a description/summary line safe to place inside a
// `/** ... */` JSDoc comment (the only place free-text spec prose lands in
// the generated file).
func jsSafe(s string) string {
	return strings.ReplaceAll(s, "*/", "* /")
}

// tsType renders a TypeSpec as a TypeScript type expression. nil (no
// response body) renders as "void" so callers building a return type don't
// need a separate nil check.
func tsType(t *TypeSpec) string {
	if t == nil {
		return "void"
	}
	switch t.Kind {
	case KindString:
		if len(t.Enum) > 0 {
			return tsEnumUnion(t.Enum)
		}
		return "string"
	case KindInteger, KindNumber:
		return "number"
	case KindBoolean:
		return "boolean"
	case KindArray:
		return tsType(t.Elem) + "[]"
	case KindMap:
		return "Record<string, " + tsType(t.Elem) + ">"
	case KindRef:
		return t.Name
	case KindUnion:
		return tsUnion(t.Variants)
	case KindObject:
		if len(t.Fields) == 0 {
			return "Record<string, unknown>"
		}
		return tsInlineObject(t)
	default:
		return "unknown"
	}
}

func tsEnumUnion(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.Quote(v)
	}
	return strings.Join(parts, " | ")
}

func tsUnion(variants []*TypeSpec) string {
	seen := map[string]bool{}
	var parts []string
	for _, v := range variants {
		s := tsType(v)
		if !seen[s] {
			seen[s] = true
			parts = append(parts, s)
		}
	}
	if len(parts) == 0 {
		return "unknown"
	}
	return strings.Join(parts, " | ")
}

func tsInlineObject(t *TypeSpec) string {
	var b strings.Builder
	b.WriteString("{ ")
	for i, f := range t.Fields {
		if i > 0 {
			b.WriteString("; ")
		}
		b.WriteString(f.Name)
		if !f.Required {
			b.WriteString("?")
		}
		b.WriteString(": ")
		b.WriteString(tsType(f.Type))
	}
	b.WriteString(" }")
	return b.String()
}

// tsEmitNamedType renders one components.schemas entry as an `export
// interface` (object with named fields), an `export type X = Y[]` (a
// top-level array schema, e.g. MenuTree), or an `export type X = ...`
// type alias for anything else (map/union/primitive/enum).
func tsEmitNamedType(b *strings.Builder, name string, t *TypeSpec) {
	if t.Doc != "" {
		fmt.Fprintf(b, "/** %s */\n", jsSafe(t.Doc))
	}
	switch {
	case t.Kind == KindArray:
		fmt.Fprintf(b, "export type %s = %s[];\n\n", name, tsType(t.Elem))
	case t.Kind == KindObject && len(t.Fields) > 0:
		fmt.Fprintf(b, "export interface %s {\n", name)
		for _, f := range t.Fields {
			if f.Doc != "" {
				fmt.Fprintf(b, "  /** %s */\n", jsSafe(f.Doc))
			}
			opt := ""
			if !f.Required {
				opt = "?"
			}
			// Property names that are not valid TS identifiers (e.g. SCIM's
			// "$ref", or an extension-namespaced key) must be quoted so the
			// emitted interface stays valid TypeScript; the wire key is
			// unchanged.
			name := f.Name
			if !isTSIdentifier(name) {
				name = strconv.Quote(name)
			}
			fmt.Fprintf(b, "  %s%s: %s;\n", name, opt, tsType(f.Type))
		}
		b.WriteString("}\n\n")
	default:
		fmt.Fprintf(b, "export type %s = %s;\n\n", name, tsType(t))
	}
}
