{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sso-server.fullname" . }}
  namespace: {{ include "sso-server.namespace" . }}
  labels:
    {{- include "sso-server.labels" . | nindent 4 }}
spec:
  {{- with .Values.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sso-server.selectorLabels" . | nindent 6 }}
{{- end }}
