apiVersion: v1
kind: Service
metadata:
  name: {{ include "sso-server.fullname" . }}
  namespace: {{ include "sso-server.namespace" . }}
  labels:
    {{- include "sso-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  selector:
    {{- include "sso-server.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $name, $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
      {{- with (index $.Values.service.nodePorts $name) }}
      nodePort: {{ . }}
      {{- end }}
    {{- end }}
