apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snaplink-sso

resources:
  - service-account.yaml
  - audit-runtime.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml

configMapGenerator:
  - name: snaplink-billing-settings
    envs:
      - settings.env
  - name: snaplink-billing-edge
    files:
      - default.conf=edge.conf

labels:
  - pairs:
      app.kubernetes.io/part-of: snaplink-sso
    includeSelectors: false
