# Code generated by cmd/gensdk (--lang=py). DO NOT EDIT.
# Source: docs/openapi.yaml (snaplink/sso HTTP API 0.1.0). Regenerate: go run ./cmd/gensdk --lang=py
#
# Minimal, hand-scoped Python client -- see docs/sdks/python/README.md for
# exactly what operationId set this covers (core OAuth2/OIDC + token
# lifecycle + self-service + a small representative admin sample) and what
# is deliberately deferred. Every method is named from the spec's
# operationId (converted to snake_case; the original is kept in each
# method's docstring) so a call site is traceable back to its
# docs/openapi.yaml operation.
#
# Stdlib only: urllib.request for transport, typing.TypedDict for wire
# shapes -- no "requests", no third-party dependency of any kind.

from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Callable, Dict, List, Optional, TypedDict, Union


class SSOError(Exception):
    """Raised on any non-2xx response; carries the parsed ErrorResponse
    fields when the body was JSON."""

    def __init__(self, status: int, error: Optional[str] = None, error_description: Optional[str] = None):
        super().__init__(error_description or error or f"sso request failed with status {status}")
        self.status = status
        self.error = error
        self.error_description = error_description


# ---- Types (generated from components.schemas) ----

class AuditEvent(TypedDict, total=False):
    actor_id: str
    actor_ip: str
    client_id: str
    hash: str
    id: str
    metadata: Dict[str, str]  # Free-form key/value pairs (tenant.*, geo.*, plus
    outcome: str
    parent_span_id: str
    prev_hash: str  # Present when WithHashChain is enabled.
    provider: str
    reason: str
    request_id: str
    session_id: str
    span_id: str
    timestamp: str
    token_id: str
    token_strategy: str
    trace_id: str
    type: str  # Canonical event type (login, logout, refresh_token_issued, ...).
    user_agent: str


class AuditEventList(TypedDict, total=False):
    count: int
    events: List[AuditEvent]


class AuthorizationDetail(TypedDict, total=False):
    """One element of RFC 9396 Rich Authorization Requests"""
    actions: List[str]  # RFC 9396 §3.3 — action verbs (read, write, transfer).
    datatypes: List[str]  # RFC 9396 §3.4 — data categories. Type-specific.
    identifier: str  # RFC 9396 §3.5 — opaque identifier scoping the grant.
    locations: List[str]  # RFC 9396 §3.2 — URIs identifying resource servers the
    privileges: List[str]  # RFC 9396 §3.6 — privilege strings within the resource.
    type: str  # URI or string identifying the action class. Allowlisted


class Button(TypedDict, total=False):
    code: str
    name: str
    permission: str


class ClientMetadata(TypedDict, total=False):
    access_token_ttl: int  # Nanoseconds.
    active: bool
    allow_passwordless_only: bool  # When true, refuses provider=password at /auth/login for this
    allowed_authenticators: List[str]
    allowed_authorization_details_types: List[str]
    allowed_pkce_methods: List[str]
    allowed_request_uris: List[str]
    allowed_resources: List[str]
    allowed_scopes: List[str]
    backchannel_logout_uri: str
    device_code_poll_interval: int
    device_code_ttl: int
    frontchannel_logout_uri: str
    id: str
    jwks: List[Dict[str, Any]]
    name: str
    post_logout_redirect_uris: List[str]
    redirect_uris: List[str]
    refresh_token_ttl: int  # Nanoseconds.
    require_par: bool
    require_pkce: bool
    require_signed_request_object: bool
    sector_identifier_uri: str
    subject_type: str
    tenant_id: str
    token_strategy: str
    userinfo_signed_response_alg: str


class DCRRequest(TypedDict, total=False):
    allowed_authenticators: List[str]
    allowed_resources: List[str]
    client_name: str
    contacts: List[str]
    grant_types: List[str]
    post_logout_redirect_uris: List[str]
    redirect_uris: List[str]
    require_pkce: bool
    response_types: List[str]
    scope: str  # Space-delimited scope list.
    tenant_id: str
    token_endpoint_auth_method: str  # `none` opts out of secret issuance (public client / PKCE
    token_strategy: str  # Names the registered TokenIssuer this client uses;


class DCRResponse(TypedDict, total=False):
    allowed_authenticators: List[str]
    allowed_resources: List[str]
    client_id: str
    client_id_issued_at: int  # Unix seconds.
    client_name: str
    client_secret: str  # Omitted when token_endpoint_auth_method=none.
    client_secret_expires_at: int  # Unix seconds; `0` means "never expires" per RFC 7591
    contacts: List[str]
    grant_types: List[str]
    post_logout_redirect_uris: List[str]
    redirect_uris: List[str]
    registration_access_token: str  # RFC 7592 management bearer — authenticates subsequent
    registration_client_uri: str
    require_pkce: bool
    response_types: List[str]
    scope: str
    token_endpoint_auth_method: str
    token_strategy: str


class DeviceCodeRequest(TypedDict, total=False):
    client_id: str
    nonce: str
    resource: List[str]
    scope: str


class DeviceCodeResponse(TypedDict, total=False):
    device_code: str  # The device polls /token with this.
    expires_in: int
    interval: int  # Minimum seconds between /token polls.
    user_code: str
    verification_uri: str
    verification_uri_complete: str  # Same URI with `?user_code=` pre-filled — QR-friendly.


class DeviceVerifyRequest(TypedDict, total=False):
    approve: bool  # `true` to authorize; `false` to deny (device's next
    user_code: str  # Case-insensitive and dash-insensitive. `WXYZ-1234`,


class IntrospectBatchResponse(TypedDict, total=False):
    """Returned instead of `IntrospectResponse` when the request used"""
    results: List[IntrospectResponse]  # One `IntrospectResponse` per requested token, in the SAME order as the request's `tokens` array.


class IntrospectRequest(TypedDict, total=False):
    client_id: str
    client_secret: str
    token: str  # The token to introspect.
    token_type_hint: str  # Lookup shortcut. Server falls back to the other store
    tokens: List[str]  # Opt-in batch mode (`oauth.introspection.batch_enabled` /


class IntrospectResponse(TypedDict, total=False):
    active: bool  # `false` covers expired / revoked / never-issued
    aud: Union[str, List[str]]
    client_id: str
    cnf: Dict[str, Any]  # RFC 7800 confirmation method. Present when the token was
    exp: int  # Unix expiry seconds.
    iat: int  # Unix issued-at seconds.
    iss: str
    jti: str
    scope: str
    sub: str
    token_type: str
    username: str


class JWK(TypedDict, total=False):
    alg: str
    crv: str
    kid: str  # First 8 bytes of sha256(pubkey), base64url-encoded.
    kty: str
    use: str
    x: str  # Base64url-encoded public key bytes.


class JWKS(TypedDict, total=False):
    keys: List[JWK]


class LoginDiscoveryResponse(TypedDict, total=False):
    providers: List[str]  # Authenticator names this client may use.


class LoginRequest(TypedDict, total=False):
    authorization_details: List[AuthorizationDetail]  # RFC 9396 Rich Authorization Requests. Each element MUST
    client_id: str  # Registered Client.ID (per cmd/sso-server/config.yaml `clients[]`).
    credential: Dict[str, str]  # Provider-specific credential map. Standard keys:
    provider: str  # Authenticator name; omit for discovery.
    resource: List[str]  # RFC 8707 resource indicators. Each value MUST be in the
    scope: List[str]
    state: str  # Opaque value echoed back to redirect-based flows.


class LoginResponse(TypedDict, total=False):
    access_token: str  # Ed25519 JWT (when client uses `token_strategy: jwt`) or opaque session token (when `session`).
    country_code: str  # ISO 3166-1 alpha-2; populated when geo middleware is wired.
    expires_in: int  # Token lifetime in seconds.
    menus: MenuTree  # Present when `permissions.embed_in_login: true`.
    permissions: List[Permission]  # Present when `permissions.embed_in_login: true`.
    recommended_language: str  # BCP-47 tag; populated when geo middleware is wired.
    refresh_token: str
    roles: List[Role]  # Present when `permissions.embed_in_login: true`.
    scope: str  # Space-delimited scope list.
    serving_region: str  # Which regional deployment served this login (e.g. `eu-west-1`).
    session_id: str  # Server-side session handle for logout calls.
    session_state: str  # OpenID Connect Session Management 1.0 §2 `session_state` — present
    token_strategy: str
    token_type: str


class LogoutRequest(TypedDict, total=False):
    session_id: str


class MFACompleteRequest(TypedDict, total=False):
    assertion: str  # WebAuthn signed-assertion JSON (the response body
    code: str  # TOTP code (RFC 6238) for the `totp` method. Six digits.
    mfa_challenge_id: str  # The opaque challenge id returned by `/auth/login` in the
    mfa_method: str  # One of the values from the `mfa_methods` array the
    params: Dict[str, str]  # Method-specific parameter map. When Params is set it wins


class MFARequiredResponse(TypedDict, total=False):
    error: str  # Sentinel value. Use this to branch — the rest of the
    iss: str  # RFC 9207 authorization-response issuer identifier.
    mfa_challenge_id: str  # Opaque challenge id to pass back on `POST /auth/mfa`.
    mfa_method_data: Dict[str, Dict[str, str]]  # Per-method server-issued challenge data for factors needing
    mfa_methods: List[str]  # Factor names the wired MFAProvider can verify. SPAs render
    state: str  # Round-tripped from the original `/auth/login` request when set.


class MenuItem(TypedDict, total=False):
    buttons: List[Button]
    children: List[MenuItem]
    icon: str
    id: str
    name: str
    path: str
    permission: str


MenuTree = List[MenuItem]


class OpenIDConfiguration(TypedDict, total=False):
    """OpenID Connect Discovery 1.0 + RFC 8414 metadata. Field set"""
    acr_values_supported: List[str]
    authorization_endpoint: str
    authorization_response_iss_parameter_supported: bool  # RFC 9207. Always true on this server.
    backchannel_logout_session_supported: bool
    backchannel_logout_supported: bool
    check_session_iframe: str  # OpenID Connect Session Management 1.0 §3. Present only when
    code_challenge_methods_supported: List[str]
    device_authorization_endpoint: str  # RFC 8628. Present only when a DeviceCodeStore is wired.
    dpop_signing_alg_values_supported: List[str]
    end_session_endpoint: str  # OIDC RP-Initiated Logout 1.0.
    frontchannel_logout_session_supported: bool
    frontchannel_logout_supported: bool
    grant_types_supported: List[str]
    id_token_encryption_alg_values_supported: List[str]  # Present only when a JWE response encrypter is wired (WithJWEResponseEncrypter).
    id_token_encryption_enc_values_supported: List[str]  # Present only when a JWE response encrypter is wired.
    id_token_signing_alg_values_supported: List[str]
    introspection_endpoint: str
    issuer: str  # Identifier the AS uses for itself. MUST equal the
    jwks_uri: str
    mtls_endpoint_aliases: Dict[str, str]
    pushed_authorization_request_endpoint: str  # RFC 9126. Present only when a PARStore is wired.
    registration_endpoint: str  # RFC 7591 DCR endpoint. Present only when DCR is enabled.
    require_pushed_authorization_requests: bool
    response_modes_supported: List[str]
    response_types_supported: List[str]
    revocation_endpoint: str
    scopes_supported: List[str]
    signed_metadata: str  # RFC 8414 §2.1 signed_metadata JWT. Present only when
    subject_types_supported: List[str]
    tls_client_certificate_bound_access_tokens: bool
    token_endpoint: str
    token_endpoint_auth_methods_supported: List[str]
    userinfo_encryption_alg_values_supported: List[str]  # Present only when a JWE response encrypter is wired.
    userinfo_encryption_enc_values_supported: List[str]  # Present only when a JWE response encrypter is wired.
    userinfo_endpoint: str
    userinfo_signing_alg_values_supported: List[str]


class PARRequest(TypedDict, total=False):
    acr_values: str
    authorization_details: List[AuthorizationDetail]  # RFC 9396 Rich Authorization Requests. JSON body delivers
    claims: Dict[str, Any]  # OIDC Core §5.5 claims request.
    client_assertion: str
    client_assertion_type: str
    client_id: str
    client_secret: str
    code_challenge: str  # RFC 7636 PKCE.
    code_challenge_method: str
    login_hint: str
    nonce: str  # OIDC nonce binding (Core §3.1.2.1).
    redirect_uri: str
    resource: List[str]
    response_mode: str  # OIDC Core response mode. The jwt / query.jwt / fragment.jwt / form_post.jwt values select JWT Secured Authorization Response Mode (JARM) and are only accepted when a JARM signer is wired (otherwise invalid_request).
    response_type: str
    scope: str  # Space-delimited scope list.
    state: str  # Opaque CSRF token the RP later checks against the
    ui_locales: str


class PARResponse(TypedDict, total=False):
    expires_in: int  # Seconds until the request_uri is consumed or expires.
    request_uri: str


class Permission(TypedDict, total=False):
    code: str
    description: str
    name: str


class RevokeRequest(TypedDict, total=False):
    client_id: str
    client_secret: str
    token: str  # The token to revoke.
    token_type_hint: str


class Role(TypedDict, total=False):
    code: str
    description: str  # Human-readable role description; surfaced on the admin
    name: str
    permissions: List[str]


class SendCodeRequest(TypedDict, total=False):
    provider: str
    target: str  # Phone number (E.164) or email address.


class Session(TypedDict, total=False):
    created_at_unix: int
    expires_at_unix: int
    id: str
    ip: str  # Device/location context captured at session creation (best-effort; honors the first-hop X-Forwarded-For trust model). Omitted when not captured.
    revoked: bool
    user_agent: str  # User-Agent captured at session creation (best-effort). Omitted when not captured.
    user_id: str


class TokenIssuance(TypedDict, total=False):
    access_token: str
    device_secret: str  # OpenID Connect Native SSO 1.0: present when the client requested the
    expires_in: int  # Access-token lifetime in seconds.
    id_token: str  # Present when the client requested `openid` scope and
    issued_token_type: str  # RFC 8693 §2.2.1 — present on token-exchange responses.
    refresh_token: str  # Present when a refresh token was issued. Family-rotated
    scope: str  # Space-delimited granted scopes.
    token_type: str  # `Bearer` for the legacy path; `DPoP` when the issuance


class TokenRequest(TypedDict, total=False):
    acr_values: str  # Space-delimited ACR list. On exchange, the dispatcher
    actor_token: str  # RFC 8693 actor_token for delegation / impersonation. When
    actor_token_type: str  # RFC 8693 token-type URI for the actor token.
    agent_session_id: str  # For `grant_type=urn:snaplink:params:oauth:grant-type:delegation`
    audience: List[str]  # RFC 8693 audience list. Merged with `resource` (RFC 8707)
    client_assertion: str  # RFC 7521 + 7523 JWT bearer client authentication. Signed
    client_assertion_type: str  # MUST be the jwt-bearer URN, or the workload-identity URN
    client_id: str  # Public client identifier. Overridden by HTTP Basic
    client_secret: str  # Confidential client secret. Body form discouraged in
    code: str  # Authorization code for `grant_type=authorization_code`.
    code_verifier: str  # RFC 7636 §4.5 PKCE verifier. Required when /auth/login
    device_code: str  # For `grant_type=urn:ietf:params:oauth:grant-type:device_code`.
    grant_type: str  # Selects the grant branch. See the endpoint description
    purp: str  # RFC 9321 Transaction Tokens — the caller-supplied purpose
    redirect_uri: str  # MUST equal the `redirect_uri` registered at /auth/login
    refresh_token: str  # For `grant_type=refresh_token`.
    request_context: str  # RFC 9321 Transaction Tokens — an OPTIONAL caller-supplied
    requested_token_type: str  # RFC 8693 §2.1 — the token type the caller wants minted.
    resource: List[str]  # RFC 8707 resource indicators. Repeat the form key for
    scope: str  # Space-delimited scope request.
    subject_token: str  # RFC 8693 subject_token — the token being exchanged. The
    subject_token_type: str  # RFC 8693 §3 token-type URI naming the subject_token's


class User(TypedDict, total=False):
    attributes: Dict[str, str]
    created_at: str
    email: str
    external_id: str
    id: str
    name: str
    provider: str
    updated_at: str


class SSOClient:
    """Minimal, hand-scoped client for the snaplink/sso HTTP API. See the
    module docstring for exactly what operation surface this covers."""

    def __init__(self, base_url: str, get_access_token: Optional[Callable[[], Optional[str]]] = None):
        self.base_url = base_url.rstrip("/")
        self.get_access_token = get_access_token

    def _request(
        self,
        method: str,
        path: str,
        query: Optional[Dict[str, Any]] = None,
        body: Optional[Any] = None,
        auth: bool = False,
    ) -> Any:
        url = self.base_url + path
        if query:
            filtered = {k: v for k, v in query.items() if v is not None}
            if filtered:
                url += "?" + urllib.parse.urlencode(filtered)
        headers = {"Accept": "application/json"}
        data = None
        if body is not None:
            headers["Content-Type"] = "application/json"
            data = json.dumps(body).encode("utf-8")
        if auth and self.get_access_token:
            token = self.get_access_token()
            if token:
                headers["Authorization"] = f"Bearer {token}"
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req) as resp:
                return _parse_body(resp.status, resp.read())
        except urllib.error.HTTPError as exc:
            payload = exc.read()
            error, error_description = _parse_error(payload)
            raise SSOError(exc.code, error, error_description) from exc

    # ---- admin ----

    def get_admin_endpoints(self) -> Dict[str, Any]:
        """Runtime endpoint inventory — every route this replica actually registered. (operationId: getAdminEndpoints)"""
        return self._request("GET", "/api/v1/admin/endpoints", auth=True)

    def query_audit_events(self, query: Optional[Dict[str, Any]] = None) -> AuditEventList:
        """Query audit events. (operationId: queryAuditEvents)"""
        return self._request("GET", "/api/v1/audit/events", query=query, auth=True)

    def get_client_by_id(self, id: str) -> ClientMetadata:
        """Fetch one Client record. (operationId: getClientByID)"""
        return self._request("GET", f"/api/v1/clients/{urllib.parse.quote(id)}")

    # ---- auth ----

    def post_login(self, body: LoginRequest) -> Union[LoginResponse, LoginDiscoveryResponse, MFARequiredResponse]:
        """Authenticate and receive a token. (operationId: postLogin)"""
        return self._request("POST", "/auth/login", body=body)

    def post_mfa_complete(self, body: MFACompleteRequest) -> LoginResponse:
        """Complete an MFA step-up challenge. (operationId: postMFAComplete)"""
        return self._request("POST", "/auth/mfa", body=body)

    def post_send_code(self, body: SendCodeRequest) -> Dict[str, Any]:
        """Send a one-time code for the named authenticator. (operationId: postSendCode)"""
        return self._request("POST", "/auth/send-code", body=body)

    def post_device_code(self, body: DeviceCodeRequest) -> DeviceCodeResponse:
        """Device-flow initiation (RFC 8628 §3.1). (operationId: postDeviceCode)"""
        return self._request("POST", "/device/code", body=body)

    def post_device_verify(self, body: DeviceVerifyRequest) -> Dict[str, Any]:
        """User-side device-code approval (RFC 8628 §3.3). (operationId: postDeviceVerify)"""
        return self._request("POST", "/device/verify", body=body, auth=True)

    def post_logout(self, body: Optional[LogoutRequest] = None) -> Dict[str, Any]:
        """Revoke the current bearer token and / or named session. (operationId: postLogout)"""
        return self._request("POST", "/logout", body=body, auth=True)

    def post_par(self, body: PARRequest) -> PARResponse:
        """Pushed Authorization Request (RFC 9126). (operationId: postPAR)"""
        return self._request("POST", "/par", body=body)

    def post_register(self, body: DCRRequest) -> DCRResponse:
        """Dynamic Client Registration (RFC 7591). (operationId: postRegister)"""
        return self._request("POST", "/register", body=body, auth=True)

    def delete_registration(self, client_id: str) -> None:
        """Deregister the client (RFC 7592 §2.3). (operationId: deleteRegistration)"""
        return self._request("DELETE", f"/register/{urllib.parse.quote(client_id)}", auth=True)

    def get_registration(self, client_id: str) -> DCRResponse:
        """Read current DCR metadata (RFC 7592 §2.1). (operationId: getRegistration)"""
        return self._request("GET", f"/register/{urllib.parse.quote(client_id)}", auth=True)

    def put_registration(self, client_id: str, body: DCRRequest) -> DCRResponse:
        """Update DCR metadata (RFC 7592 §2.2). (operationId: putRegistration)"""
        return self._request("PUT", f"/register/{urllib.parse.quote(client_id)}", body=body, auth=True)

    def post_token(self, body: TokenRequest) -> TokenIssuance:
        """OAuth 2.0 token endpoint (RFC 6749 §3.2). (operationId: postToken)"""
        return self._request("POST", "/token", body=body)

    def post_introspect(self, body: IntrospectRequest) -> Union[IntrospectResponse, IntrospectBatchResponse]:
        """OAuth 2.0 token introspection (RFC 7662). (operationId: postIntrospect)"""
        return self._request("POST", "/token/introspect", body=body)

    def post_revoke(self, body: RevokeRequest) -> None:
        """OAuth 2.0 token revocation (RFC 7009). (operationId: postRevoke)"""
        return self._request("POST", "/token/revoke", body=body)

    def post_revoke_all(self) -> Dict[str, Any]:
        """Bulk revoke every refresh token bound to the bearer's subject. (operationId: postRevokeAll)"""
        return self._request("POST", "/token/revoke-all", auth=True)

    # ---- discovery ----

    def get_jwks(self) -> JWKS:
        """JSON Web Key Set for local JWT verification. (operationId: getJWKS)"""
        return self._request("GET", "/.well-known/jwks.json")

    def get_o_auth_authorization_server_metadata(self) -> OpenIDConfiguration:
        """RFC 8414 OAuth 2.0 Authorization Server Metadata (alias). (operationId: getOAuthAuthorizationServerMetadata)"""
        return self._request("GET", "/.well-known/oauth-authorization-server")

    def get_open_id_configuration(self) -> OpenIDConfiguration:
        """OpenID Connect Discovery 1.0 document. (operationId: getOpenIDConfiguration)"""
        return self._request("GET", "/.well-known/openid-configuration")

    # ---- me ----

    def get_my_menus(self) -> MenuTree:
        """Menu tree the bearer's subject is authorized to see. (operationId: getMyMenus)"""
        return self._request("GET", "/menus/me", auth=True)

    def get_my_permissions(self) -> List[Permission]:
        """Permissions of the bearer's subject for the inferred client. (operationId: getMyPermissions)"""
        return self._request("GET", "/permissions/me", auth=True)

    def get_my_roles(self) -> List[Role]:
        """Roles of the bearer's subject for the inferred client. (operationId: getMyRoles)"""
        return self._request("GET", "/roles/me", auth=True)

    # ---- self-service ----

    def list_my_consents(self) -> Dict[str, Any]:
        """List the authenticated user's consent grants. (operationId: listMyConsents)"""
        return self._request("GET", "/consents/me", auth=True)

    def get_me(self) -> Dict[str, Any]:
        """Authenticated self-service account overview. (operationId: getMe)"""
        return self._request("GET", "/me", auth=True)

    def patch_me(self, body: Dict[str, Any]) -> Dict[str, Any]:
        """Authenticated self-service profile update. (operationId: patchMe)"""
        return self._request("PATCH", "/me", body=body, auth=True)

    def list_my_mfa_factors(self) -> Dict[str, Any]:
        """List the authenticated user's registered second factors. (operationId: listMyMFAFactors)"""
        return self._request("GET", "/me/mfa", auth=True)

    def change_my_password(self, body: Dict[str, Any]) -> None:
        """Authenticated self-service password change. (operationId: changeMyPassword)"""
        return self._request("POST", "/me/password", body=body, auth=True)

    def revoke_my_sessions(self, query: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Sign out everywhere — revoke the user's sessions in bulk. (operationId: revokeMySessions)"""
        return self._request("DELETE", "/sessions/me", query=query, auth=True)

    def list_my_sessions(self) -> Dict[str, Any]:
        """List the authenticated user's own active sessions. (operationId: listMySessions)"""
        return self._request("GET", "/sessions/me", auth=True)

    # ---- userinfo ----

    def get_user_info(self) -> User:
        """Fetch the user record for the bearer's subject. (operationId: getUserInfo)"""
        return self._request("GET", "/userinfo", auth=True)


def _parse_body(status: int, raw: bytes) -> Any:
    if status == 204 or not raw:
        return None
    return json.loads(raw)


def _parse_error(payload: bytes) -> "tuple[Optional[str], Optional[str]]":
    if not payload:
        return None, None
    try:
        parsed = json.loads(payload)
    except ValueError:
        return None, None
    return parsed.get("error"), parsed.get("error_description")
