package main

import "github.com/snaplink/sso/spi"

import (
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/snaplink/sso/config"
)

func quietLogger() spi.Logger { return spi.NopLogger{} }

func TestBuildDPoPNonceProvider_AutoGeneratedWhenKeyFileEmpty(t *testing.T) {
	p, err := buildDPoPNonceProvider(config.DPoPNonceConfig{
		Enabled: true,
		TTL:     time.Minute,
	}, quietLogger())
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	n, err := p.Issue()
	if err != nil {
		t.Fatalf("issue: %v", err)
	}
	if err := p.Verify(n); err != nil {
		t.Fatalf("verify roundtrip: %v", err)
	}
}

func TestBuildDPoPNonceProvider_FromHexKeyFile(t *testing.T) {
	dir := t.TempDir()
	keyPath := filepath.Join(dir, "nonce.key")
	rawKey := strings.Repeat("ab", 32) // 64 hex chars = 32 bytes
	if err := os.WriteFile(keyPath, []byte(rawKey+"\n"), 0o600); err != nil {
		t.Fatalf("write key: %v", err)
	}

	// Both providers must verify each other's nonces — proves the
	// shared key path actually used the file contents, not a random
	// fallback.
	a, err := buildDPoPNonceProvider(config.DPoPNonceConfig{
		Enabled: true, KeyFile: keyPath, TTL: time.Minute,
	}, quietLogger())
	if err != nil {
		t.Fatalf("a: %v", err)
	}
	b, err := buildDPoPNonceProvider(config.DPoPNonceConfig{
		Enabled: true, KeyFile: keyPath, TTL: time.Minute,
	}, quietLogger())
	if err != nil {
		t.Fatalf("b: %v", err)
	}
	n, _ := a.Issue()
	if err := b.Verify(n); err != nil {
		t.Fatalf("cross-replica verify on shared key file: %v", err)
	}
}

func TestBuildDPoPNonceProvider_FromRawBytesKeyFile(t *testing.T) {
	// Non-hex bytes still work: provider falls back to raw-bytes
	// interpretation when hex decode fails.
	dir := t.TempDir()
	keyPath := filepath.Join(dir, "nonce.key")
	raw := []byte("xxxx not-hex-at-all but at-least-16-bytes!")
	if err := os.WriteFile(keyPath, raw, 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}
	p, err := buildDPoPNonceProvider(config.DPoPNonceConfig{
		Enabled: true, KeyFile: keyPath, TTL: time.Minute,
	}, quietLogger())
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	n, _ := p.Issue()
	if err := p.Verify(n); err != nil {
		t.Fatalf("verify: %v", err)
	}
}

func TestBuildDPoPNonceProvider_HexShorterThan16BytesFallsBackToRaw(t *testing.T) {
	// Hex of fewer than 32 chars (16 bytes) decodes successfully but
	// the SDK rejects the key as too short — provider should treat
	// the file as raw bytes instead. We still need at least 16 raw
	// bytes to pass the SDK gate. So write 20-char hex string
	// (10 bytes hex-decoded = too short → falls back to raw "61626c..."
	// which is 20 chars = enough raw bytes).
	dir := t.TempDir()
	keyPath := filepath.Join(dir, "nonce.key")
	// 20 hex chars: hex-decode yields 10 bytes (rejected as too short),
	// raw bytes = 20 (accepted).
	if err := os.WriteFile(keyPath, []byte("0123456789abcdef0123"), 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}
	if _, err := buildDPoPNonceProvider(config.DPoPNonceConfig{
		Enabled: true, KeyFile: keyPath, TTL: time.Minute,
	}, quietLogger()); err != nil {
		t.Fatalf("build: %v", err)
	}
}

func TestBuildDPoPNonceProvider_MissingFileReturnsError(t *testing.T) {
	_, err := buildDPoPNonceProvider(config.DPoPNonceConfig{
		Enabled: true, KeyFile: "/no/such/file",
	}, quietLogger())
	if err == nil {
		t.Fatal("expected error on missing key file, got nil")
	}
}

// Compile-time guard: changing the encoding/hex import contract here
// means the production buildDPoPNonceProvider should keep parsing both
// hex- and raw-bytes forms.
var _ = hex.EncodeToString
